# -*- mode: python ; coding: utf-8 -*-

# ── Version SSOT: core.py APP_VERSION drives the Win32 version resource ──────
# version_info.txt is GENERATED here from core.APP_VERSION at build time, so the
# exe's file-version can never drift from the app's reported version again
# (bug #2: a b6-labelled exe shipped as b8; the b26 SSOT shipped as b27). Do NOT
# hand-edit Pak-Rat/version_info.txt — this block overwrites it every build.
import re as _re
from pathlib import Path as _Path
_core = (_Path('Pak-Rat') / 'core.py').read_text(encoding='utf-8')
_m = _re.search(r'APP_VERSION\s*=\s*["\']([^"\']+)["\']', _core)
if not _m:
    raise SystemExit('Pak-Rat.spec: could not read APP_VERSION from core.py')
_ver = _m.group(1)                                    # e.g. 3.0.0-beta28
_base = _ver.split('-', 1)[0]                          # 3.0.0
_bm = _re.search(r'beta(\d+)', _ver)
_build = int(_bm.group(1)) if _bm else 0
_maj, _min, _pat = (list(map(int, _base.split('.'))) + [0, 0, 0])[:3]
_vt = (_maj, _min, _pat, _build)
_vinfo = f'''# AUTO-GENERATED by Pak-Rat.spec from core.APP_VERSION="{_ver}" — do NOT edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={_vt},
    prodvers={_vt},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Pak-Rat'),
        StringStruct('FileDescription', 'Pak-Rat - RetroRewind mod asset injector'),
        StringStruct('FileVersion', '{_maj}.{_min}.{_pat}.{_build}'),
        StringStruct('InternalName', 'Pak-Rat'),
        StringStruct('LegalCopyright', '(c) 2026 Yodah'),
        StringStruct('OriginalFilename', 'Pak-Rat.exe'),
        StringStruct('ProductName', 'Pak-Rat'),
        StringStruct('ProductVersion', '{_ver}')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
'''
(_Path('Pak-Rat') / 'version_info.txt').write_text(_vinfo, encoding='utf-8')


a = Analysis(
    ['Pak-Rat\\pak_rat.py'],
    pathex=['Pak-Rat'],
    binaries=[],
    datas=[('Pak-Rat/Pak-Rat.ico', '.'), ('Pak-Rat/Pak-Rat.png', '.'), ('Pak-Rat/vendor', 'vendor')],
    hiddenimports=['core', 'cook', 'inject', 'relink', 'extract_mesh', 'PIL.Image',
                   'pythonnet', 'clr', 'clr_loader'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PySide6.QtQml', 'PySide6.QtQuick', 'PySide6.QtQuick3D', 'PySide6.QtQuickWidgets', 'PySide6.QtQuickControls2', 'PySide6.QtNetwork', 'PySide6.QtPdf', 'PySide6.QtPdfWidgets', 'PySide6.QtOpenGL', 'PySide6.QtOpenGLWidgets', 'PySide6.QtWebEngineCore', 'PySide6.QtWebEngineWidgets', 'PySide6.QtWebChannel', 'PySide6.QtWebSockets', 'PySide6.QtMultimedia', 'PySide6.QtMultimediaWidgets', 'PySide6.QtCharts', 'PySide6.QtDataVisualization', 'PySide6.QtSql', 'PySide6.QtTest', 'PySide6.QtSvg', 'PySide6.QtSvgWidgets', 'PySide6.QtPrintSupport', 'PySide6.QtXml', 'PySide6.QtConcurrent', 'PySide6.QtPositioning', 'PySide6.QtSensors', 'PySide6.QtSerialPort', 'PySide6.QtBluetooth', 'PySide6.QtNfc', 'PySide6.QtHelp', 'PySide6.QtUiTools', 'PySide6.QtDesigner', 'PySide6.QtScxml', 'PySide6.QtStateMachine', 'PySide6.QtRemoteObjects', 'PySide6.QtTextToSpeech', 'PySide6.QtSpatialAudio', 'PySide6.Qt3DCore', 'PySide6.Qt3DRender', 'PySide6.QtDBus', 'PySide6.QtNetworkAuth', 'PySide6.QtLocation', 'tkinter', 'numpy', 'unittest', 'pydoc', 'lib2to3', 'pdb'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Pak-Rat',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['Pak-Rat\\Pak-Rat.ico'],
    version='Pak-Rat\\version_info.txt',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='Pak-Rat',
)
