"""
Pak Rat v3 — "Add Asset" injection engine.

Adds genuinely NEW content to Retro Rewind (not a swap). The catalogue lists
purchasable/placeable items via Blueprint functions
`Return Catalogue <Category> product class` inside UI_Catalogue_Widget. Editing
that widget's compiled bytecode by hand is a dead end (a correct edit is a full
Kismet recompile, not a byte insert). So v3 registers new items at RUNTIME with
a tiny UE4SS Lua mod that hooks those functions and appends the new class to the
returned array — proven in-game, no widget edit, no crash.

Pipeline:
  1. Cook the user's model into a Decoration-derived Blueprint at a NEW /Game
     path (reuses the v2 UE cooker) so it is a real, loadable class.
  2. Pack the cooked asset into a loose `_P.pak`.
  3. Generate a UE4SS Lua mod that LoadAsset()s each new class and appends it to
     its catalogue category at runtime, plus an INI manifest tracking everything
     added (so re-runs are idempotent / additive).

Requires UE4SS installed in the game (for the runtime hook) AND Unreal Engine
(for the cook). The GUI gates the mode on `ue4ss_available()`.
"""
from __future__ import annotations

import configparser
import datetime
import shutil
from pathlib import Path

import core
import cook
import relink

# Category -> the widget function that returns that category's class array.
CATEGORIES = ("Decoration", "Equipmement", "Station", "Container")
CATEGORY_LABELS = {
    "Decoration": "Decorations",
    "Equipmement": "Equipment",
    "Station": "Stations",
    "Container": "Shelves",
}
WIDGET_CLASS = ("/Game/VideoStore/asset/prop/catalogue/"
                "UI_Catalogue_Widget.UI_Catalogue_Widget_C")

MOD_NAME = "PakRatInjector"

# Content types shown on the v3 "what are you adding?" step. Each maps to a
# catalogue product-class function (`category`). Only types with mapped=True are
# selectable in the GUI; the rest are placeholders until their catalogue path is
# reverse-engineered and proven. Order = display order.
# Shelves(Container) + Equipment(Equipmement) use the SAME proven catalogue hook
# as Decoration — `Return Catalogue <category> product class` on UI_Catalogue_Widget,
# which the generated Lua already generalizes over. The cook yields a Decoration-
# derived BP; `category` just routes which catalogue tab it's appended to.
# Snacks/Drinks/Toys ARE catalogue items via the 2-TIER vending-box path: the BOX is
# the SKU, and its CDO holds a product-class array we repoint to a cloned product (see
# the Container EXEMPLARS below + _clone_container_box). All three box name-maps were
# verified against the R: base pak 2026-07-07, so the clone/box_repoint rename strings
# are confirmed correct — the category is now live.
CONTENT_TYPES = [
    {"key": "Decoration",             "category": "Decoration",  "mapped": True},
    {"key": "Equipment",              "category": "Equipmement", "mapped": True},
    {"key": "Snacks, Drinks & Toys",  "category": "Container",   "mapped": True},
]


def mapped_content_types() -> list[dict]:
    return [t for t in CONTENT_TYPES if t["mapped"]]


def content_type(key: str) -> dict | None:
    for t in CONTENT_TYPES:
        if t["key"] == key:
            return t
    return None


# ---------------------------------------------------------------------------
# UE4SS discovery (mirrors cook.ue_available for the GUI gate)
# ---------------------------------------------------------------------------
def _game_binaries_dir() -> Path | None:
    """<...>/RetroRewind/RetroRewind/Binaries/Win64 — sibling of Content/Paks."""
    try:
        paks = core._rr_paks_dir()          # <...>/RetroRewind/Content/Paks
    except Exception:
        return None
    win64 = paks.parent.parent / "Binaries" / "Win64"
    return win64 if win64.is_dir() else None


def ue4ss_dir() -> Path | None:
    win64 = _game_binaries_dir()
    if not win64:
        return None
    d = win64 / "ue4ss"
    if (d / "UE4SS.dll").is_file() or (d / "Mods").is_dir():
        return d
    return None


def ue4ss_mods_dir() -> Path | None:
    d = ue4ss_dir()
    return (d / "Mods") if d else None


def ue4ss_available() -> bool:
    return ue4ss_dir() is not None


# ---------------------------------------------------------------------------
# Lua injector + INI manifest generation
# ---------------------------------------------------------------------------
_LUA_HEADER = """-- ============================================================
-- PakRat Injector  (auto-generated by Pak Rat v3 — do not hand-edit)
-- Registers added items into the Retro Rewind catalogue at runtime by
-- hooking the per-category product-class functions and appending the new
-- classes to the returned array. Proven mechanism; no widget bytecode edit.
-- Regenerate by re-running Pak Rat "Add Asset".
-- ============================================================
local WIDGET_CLASS = "%(widget)s"

-- items[category] = { { pkg=<package path>, cls=<class object path> }, ... }
local ITEMS = %(items)s

local function log(m) print("[PakRatInjector] " .. tostring(m) .. "\\n") end
local function valid(o) return o and o:IsValid() end
local function findObj(p) local ok,o = pcall(StaticFindObject, p); if ok then return o end return nil end

-- Resolve (loading if needed) every class up front; cache the UClass objects.
local RESOLVED = {}   -- category -> { classObj, ... }
local function resolveAll()
    for cat, list in pairs(ITEMS) do
        RESOLVED[cat] = RESOLVED[cat] or {}
        for _, it in ipairs(list) do
            local c = findObj(it.cls)
            if not valid(c) then pcall(LoadAsset, it.pkg); c = findObj(it.cls) end
            if valid(c) then
                RESOLVED[cat][#RESOLVED[cat] + 1] = c
                log("resolved " .. it.cls)
            else
                log("FAILED to load " .. it.cls)
            end
        end
    end
end

local function makeAppender(cat)
    return function(Context, ReturnValue)
        pcall(function()
            if ReturnValue == nil then return end
            local arr = ReturnValue:get(); if arr == nil then return end
            local list = RESOLVED[cat]; if not list then return end
            for _, c in ipairs(list) do
                if valid(c) then arr[arr:GetArrayNum() + 1] = c end
            end
        end)
    end
end

local hooked = false
local function register()
    if hooked then return end
    resolveAll()
    for _, cat in ipairs({ %(cats)s }) do
        if ITEMS[cat] then
            local fn = WIDGET_CLASS .. ":Return Catalogue " .. cat .. " product class"
            local ok = pcall(function() RegisterHook(fn, makeAppender(cat), function() end) end)
            log((ok and "hooked " or "hook FAILED ") .. fn)
        end
    end
    hooked = true
end

-- The widget class isn't loaded at startup; register when it first appears.
NotifyOnNewObject(WIDGET_CLASS, function() register() end)
log("loaded")
"""


def _lua_table(items_by_cat: dict[str, list[dict]]) -> str:
    """Render the ITEMS Lua table literal."""
    lines = ["{"]
    for cat, lst in items_by_cat.items():
        lines.append(f'  ["{cat}"] = {{')
        for it in lst:
            lines.append(f'    {{ pkg="{it["pkg"]}", cls="{it["cls"]}" }},')
        lines.append("  },")
    lines.append("}")
    return "\n".join(lines)


def write_injector_mod(items_by_cat: dict[str, list[dict]],
                       mods_dir: Path | None = None) -> Path:
    """Write the UE4SS Lua mod that registers every item. Returns the mod dir."""
    mods_dir = mods_dir or ue4ss_mods_dir()
    if not mods_dir:
        raise RuntimeError("UE4SS Mods folder not found — is UE4SS installed?")
    mod = mods_dir / MOD_NAME
    (mod / "Scripts").mkdir(parents=True, exist_ok=True)
    (mod / "enabled.txt").write_text("", encoding="utf-8")

    cats = ", ".join(f'"{c}"' for c in items_by_cat)
    lua = _LUA_HEADER % {
        "widget": WIDGET_CLASS,
        "items": _lua_table(items_by_cat),
        "cats": cats,
    }
    (mod / "Scripts" / "main.lua").write_text(lua, encoding="utf-8")

    # Ensure the mod is listed+enabled in mods.txt (UE4SS load list).
    _ensure_mods_txt(mods_dir)
    return mod


def _ensure_mods_txt(mods_dir: Path) -> None:
    txt = mods_dir / "mods.txt"
    line = f"{MOD_NAME} : 1"
    try:
        existing = txt.read_text(encoding="utf-8") if txt.is_file() else ""
    except Exception:
        existing = ""
    if MOD_NAME in existing:
        return
    sep = "" if existing.endswith("\n") or not existing else "\n"
    with txt.open("a", encoding="utf-8") as f:
        f.write(sep + line + "\n")


# ---------------------------------------------------------------------------
# INI manifest — the registry of record for everything Pak Rat has added.
# ---------------------------------------------------------------------------
def manifest_path() -> Path:
    return cook.home() / "additions.ini"


def load_manifest() -> configparser.ConfigParser:
    cp = configparser.ConfigParser()
    p = manifest_path()
    if p.is_file():
        cp.read(p, encoding="utf-8")
    return cp


def manifest_items() -> dict[str, list[dict]]:
    """Read the manifest into {category: [{pkg, cls, name}, ...]}."""
    cp = load_manifest()
    out: dict[str, list[dict]] = {}
    for sec in cp.sections():
        if not sec.startswith("item:"):
            continue
        d = cp[sec]
        cat = d.get("category", "Decoration")
        price = d.get("price", "")
        out.setdefault(cat, []).append({
            "pkg": d.get("pkg", ""), "cls": d.get("cls", ""),
            "name": d.get("name", sec[5:]),
            "price": float(price) if price else None,
            # widget sibling anchor — persisted so re-adds don't regress a wall /
            # equipment item back to the category default (Couch_C floor sibling).
            "sibling": d.get("sibling") or None,
        })
    return out


def save_manifest(items_by_cat: dict[str, list[dict]]) -> Path:
    cp = configparser.ConfigParser()
    cp["pakrat"] = {
        "version": core.APP_VERSION,
        "updated": datetime.datetime.now().isoformat(timespec="seconds"),
    }
    for cat, lst in items_by_cat.items():
        for it in lst:
            key = "item:" + it.get("name", it["cls"].rsplit(".", 1)[-1])
            cp[key] = {
                "category": cat, "name": it.get("name", ""),
                "pkg": it["pkg"], "cls": it["cls"],
                "price": str(it.get("price") if it.get("price") is not None else ""),
                "sibling": it.get("sibling") or "",
            }
    p = manifest_path()
    with p.open("w", encoding="utf-8") as f:
        cp.write(f)
    return p


def has_additions() -> bool:
    """True if any items were previously added (drives the Page-1 label flip)."""
    return bool(manifest_items())


def reset_additions() -> None:
    """Wipe the additions manifest AND the persistent asset library so the next Add
    starts from a genuinely clean catalogue (metadata + staged package files both go).
    Fixes #5: the manifest is additive and replays EVERY past item into each generated
    pak, so stale test entries showed up as extra catalogue items."""
    try:
        manifest_path().unlink()
    except FileNotFoundError:
        pass
    shutil.rmtree(asset_library(), ignore_errors=True)
    try:
        _pak_name_file().unlink()          # forget the saved name -> next add prompts
    except FileNotFoundError:
        pass


# ---------------------------------------------------------------------------
# Persistent asset library — every added item's staged package files (the cloned
# item .uasset/.uexp carrying its CDO, the cooked mesh, the custom thumbnail) are
# kept here under their real pak-tree paths. Every Add then rebuilds ONE pak from
# the WHOLE library and overwrites the previous one, so the catalogue extends
# without bound and no earlier item is ever dropped. Without this store the pak
# only held the newest run's files, so a second Add killed the first item's assets.
# It lives in the writable Pak Rat home (LOCALAPPDATA/PakRat — survives app
# updates, unlike the read-only _internal bundle); additions.ini is its index.
# ---------------------------------------------------------------------------
ADDITIONS_PAK = "zzz_PakRat_Additions_P.pak"   # fixed name -> each deploy overwrites


def asset_library() -> Path:
    d = cook.home() / "asset_library"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _merge_tree(src: Path, dst: Path) -> None:
    """Copy every file under `src` into `dst`, preserving the relative pak-tree
    layout. Overwrites same-path files; leaves unrelated files in `dst` intact."""
    for p in src.rglob("*"):
        if p.is_file():
            out = dst / p.relative_to(src)
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, out)


# The mod file name is chosen ONCE (first add) and reused on every later add, so the
# deployed pak keeps the same name and each add overwrites it in ~mods rather than
# leaving a trail of conflicting paks. reset_additions() clears it (start fresh).
def _pak_name_file() -> Path:
    return cook.home() / "pak_name.txt"


def saved_pak_name() -> str | None:
    """The pak name saved on the first add, or None if none saved yet."""
    p = _pak_name_file()
    if p.is_file():
        return p.read_text(encoding="utf-8").strip() or None
    return None


def save_pak_name(name: str) -> None:
    _pak_name_file().write_text(name.strip(), encoding="utf-8")


# ---------------------------------------------------------------------------
# Cook: FBX -> Decoration-derived Blueprint at a NEW /Game path.
#
# EXPERIMENTAL (beta1): the runtime injection mechanism is proven in-game, but
# cooking a brand-new Decoration Blueprint (vs a swap) is new. The cooked BP
# derives from a stub `Decoration` whose parent import resolves to the REAL
# game Decoration class at runtime (same stub-retarget trick v2 uses for
# materials), so it is a genuine TSubclassOf<Decoration>. Product metadata
# (price/name) falls back to the base Decoration defaults for now.
# ---------------------------------------------------------------------------
# EXEMPLARS: a real, in-game, LOADABLE catalogue item per type that we CLONE.
# Deriving a new BP from a stub Decoration fails to load (the cooked class binds to
# the game's real Decoration_C at runtime and mismatches the stub it was compiled
# against). A clone of a real item instead INHERITS that item's correct link to the
# real base class for free — so it loads. We only rename it (new unique identity) and
# repoint its mesh, both as SAME-LENGTH byte edits (the one edit class proven 100%
# reliable — no offsets shift, no package rewrite, no UAssetAPI shipped).
#   self_path / class_token / mesh_path / mesh_name are the exact strings we swap.
#   `asset` len sets the item-token length; `mesh_name` len sets the mesh-token length.
MESH_ROOT = "/Game/VideoStore/asset/meshes"
# Real, in-game LOADABLE items we clone — now keyed by exemplar id (the user picks
# which base on the Exemplar page). `placement` splits floor vs wall-mounted so a
# model can be added either way. `cdo_title_key` BYTE LENGTH sets the added item's
# token length so relink.setcdo stays length-neutral (no CDO shift -> no price-0 /
# blank-thumb / crash regression). All paths verified against the base pak.
EXEMPLARS = {
    "couch": {
        "id": "couch", "label": "Couch", "placement": "floor",
        "category": "Decoration",
        "pak_dir": "RetroRewind/Content/VideoStore/asset/prop/decoration/Couch",
        "asset": "Couch",
        "self_path": "/Game/VideoStore/asset/prop/decoration/Couch/Couch",
        "class_token": "Couch_C",
        # This is the mesh reference that actually exists inside the Couch BP and
        # must be renamed to the newly cooked user mesh.
        "mesh_path": "/Game/VideoStore/asset/meshes/LA_Chair_A_01",
        "mesh_name": "LA_Chair_A_01",
        # Material DONOR (discovery ONLY): a clean, self-contained MI whose params
        # directly own bc/n/ram. Pak Rat clones this MI per item and rewrites its
        # Base Color / Normal / RAM texture PARAMETER VALUES to the per-item textures
        # (full-res, .ubulk preserved). The Chair's parameterized master material
        # (cross-library textures + Global AO) is deliberately NOT used as the donor.
        "material_mesh_path": "/Game/VideoStore/asset/meshes/DECO/LA_DECO_Balloons_Hearts_A_01",
        "cdo_title_key": "Interface_Product_Decoration_Couch",
        "thumb_path": "/Game/VideoStore/asset/prop/decoration/Couch/T_Decoration_Couch_T",
        "thumb_name": "T_Decoration_Couch_T",
        "default_price": 100.0,
        # Widget import the clone is inserted BESIDE in the product-class array.
        # In-game placement follows the array neighbour (floor beside Couch_C =
        # floor placement), so wall items must anchor on a WALL sibling instead.
        "widget_sibling": "Couch_C",
    },
    "poster_frame": {
        "id": "poster_frame", "label": "Movie Poster (wall-mounted)", "placement": "wall",
        "category": "Decoration",
        "pak_dir": "RetroRewind/Content/VideoStore/asset/prop/PosterFrame",
        "asset": "PosterFrame",
        "self_path": "/Game/VideoStore/asset/prop/PosterFrame/PosterFrame",
        "class_token": "PosterFrame_C",
        # This is the mesh reference that actually exists inside the PosterFrame BP
        # and must be renamed to the newly cooked user mesh.
        "mesh_path": "/Game/VideoStore/asset/meshes/LA_PosterFrame_Big_01",
        "mesh_name": "LA_PosterFrame_Big_01",
        # Material DONOR (discovery ONLY): clean self-contained wall donor whose MI
        # directly owns bc/n/ram. Cloned + texture PARAMETER VALUES rewritten per item
        # (full-res, .ubulk preserved). See couch note. NOTE: placement still rides the
        # PosterFrame BP — wall poster-specific behaviour pending Yodah's wall patch.
        "material_mesh_path": "/Game/VideoStore/asset/meshes/DECO/LA_DECO_SwordShield_A_01",
        "cdo_title_key": "Interface_Product_Decoration_Frame",
        "thumb_path": "/Game/VideoStore/asset/prop/PosterFrame/T_PosterFrame_01_T",
        "thumb_name": "T_PosterFrame_01_T",
        "default_price": 100.0,
        # Wall anchor — PosterFrame_C is a Decoration widget import that wall-mounts.
        # THE wall-mount fix: register cloned wall items beside THIS, not Couch_C.
        "widget_sibling": "PosterFrame_C",
    },
    # --- Equipment (keep_mesh): cloned as a NEW identity that KEEPS the vanilla
    # mesh + materials, so it looks like the base machine and needs no user model
    # or UE cook. Registered on the real Equipmement product-class fn beside
    # Pinball-Machine_A_C (the only equipment class present in the widget imports;
    # Arcade_C is NOT a widget import). Equipment has no Interface_Product_* CDO
    # title key, so build_added_item skips the length-neutral setcdo for these.
    "arcade": {
        "id": "arcade", "label": "Arcade Machine", "placement": "floor",
        "category": "Equipmement", "keep_mesh": True,
        "pak_dir": "RetroRewind/Content/VideoStore/asset/prop/arcade",
        "asset": "Arcade",
        "self_path": "/Game/VideoStore/asset/prop/arcade/Arcade",
        "class_token": "Arcade_C",
        "mesh_path": "/Game/VideoStore/asset/meshes/LA_Arcade_A_01",
        "mesh_name": "LA_Arcade_A_01",
        "thumb_path": "/Game/VideoStore/asset/prop/arcade/T_Arcade_01_T",
        "thumb_name": "T_Arcade_01_T",
        "default_price": 100.0,
        "widget_sibling": "Pinball-Machine_A_C",
        # setcdo swaps this vanilla title key (len 40) for Interface_ModKit_<item>_Title
        # of the SAME byte length -> item token = 40 - 23 = 17 chars (length-neutral).
        "cdo_title_key": "Interface_Statistic-LevelUp_Arcade_Title",
        # Body/colour reskin (Arcade_D recipe): the body base-colour texture the two
        # colour MIs sample. Repointing the cloned MIs to a fresh copy recolours only
        # this new machine (additive). The screen (VideoClips) is SKU/BP-driven, not
        # in an MI — so an optional screen picker is best-effort file-copy only.
        "body_texture": {
            "path": "/Game/VideoStore/asset/textures/T_Arcade_A_01/T_Arcade_A_01_bc",
            "name": "T_Arcade_A_01_bc",
        },
        "color_materials": [
            {"path": "/Game/VideoStore/asset/textures/T_Arcade_A_01/MI_Arcade_A_01",
             "name": "MI_Arcade_A_01", "body": True},
            {"path": "/Game/VideoStore/asset/textures/T_Arcade_A_01/MI_Arcade_A_02",
             "name": "MI_Arcade_A_02", "body": False},
        ],
        # Screen/display: the video-clips texture the arcade shows on its screen. It
        # is applied by the BP's SKU logic, not an MI in the clone, so it is swapped
        # by OVERRIDING the texture at its own path (the second, optional picker).
        "screen_texture": {
            "path": "/Game/VideoStore/asset/textures/T_Arcade_A_01/T_Arcade_A_VideoClips_01_bc",
            "name": "T_Arcade_A_VideoClips_01_bc",
        },
    },
    "pinball": {
        "id": "pinball", "label": "Pinball Machine", "placement": "floor",
        "category": "Equipmement", "keep_mesh": True,
        "pak_dir": "RetroRewind/Content/VideoStore/asset/prop/Pinball",
        "asset": "Pinball-Machine_A",
        "self_path": "/Game/VideoStore/asset/prop/Pinball/Pinball-Machine_A",
        "class_token": "Pinball-Machine_A_C",
        # Pinball-Machine_A inherits its mesh from Pinball-Machine_Base (no own
        # mesh ref). mesh_path/name only feed _slot_tokens' length math here.
        "mesh_path": "/Game/VideoStore/asset/prop/Pinball/Pinball-Machine_Base",
        "mesh_name": "Pinball-Machine_Base",
        "thumb_path": "/Game/VideoStore/asset/prop/Pinball/T_Pinball-Thumbnail",
        "thumb_name": "T_Pinball-Thumbnail",
        "default_price": 100.0,
        "widget_sibling": "Pinball-Machine_A_C",
        # Title key len 41 -> item token 18 (length-neutral).
        "cdo_title_key": "Interface_Statistic-LevelUp_Pinball_Title",
        # Pinball's colour MI lives on its shared Base/mesh (not this BP's name map),
        # so a per-item MI-clone repoint isn't reachable — the body/colour texture is
        # swapped by OVERRIDING it at its own path (functional; shared across pinballs).
        "body_override": {
            "path": "/Game/VideoStore/asset/textures/T_Pinball_A_01/T_PinBall_A_01_bc",
            "name": "T_PinBall_A_01_bc",
        },
    },
    # --- Container (snack/drink/toy): 2-TIER. The catalogue sells a vending BOX
    # (SnackBox_Snack_C) whose CDO holds an ARRAY of product-CLASS refs (the shelf
    # it dispenses). TIER 1 = the PRODUCT (Snack_Candy-A_C -> Snack_Base_C) is a
    # couch/arcade-style item: name-map mesh swap + Product Name title-key + Image
    # Thumbnail (all the fields above map to the PRODUCT). TIER 2 = the BOX, in
    # `box` below: clone it, rename its product-class ref to the cloned product,
    # box_repoint ALL shelf slots to that product, and register THE BOX in the
    # Container catalogue fn. NOTE for the pipeline (build_added_item Container
    # branch — Ares to wire): the product CDO stores thumbnail refs (NOT a price
    # double) right after the title-key, so setcdo MUST be name-only (price=None)
    # for products or it corrupts the thumbnail; product Price is inherited from
    # Snack_Base_C (custom per-product price = a separate add-property step).
    # drink/toy = identical shape; fill their product-class specifics via the same
    # decode (drink product-class + LA_ mesh + Interface_Product_* key; toy same).
    "snack": {
        "id": "snack", "label": "Snack (vending box)", "placement": "floor",
        "category": "Container",
        "pak_dir": "RetroRewind/Content/VideoStore/asset/prop/Snack/Candy",
        "asset": "Snack_Candy-A",
        "self_path": "/Game/VideoStore/asset/prop/Snack/Candy/Snack_Candy-A",
        "class_token": "Snack_Candy-A_C",
        "mesh_path": "/Game/VideoStore/asset/meshes/LA_Candy_Box_A_01",
        "mesh_name": "LA_Candy_Box_A_01",
        # 32 chars -> item token = 32 - _TITLE_AFFIX(23) = 9 (length-neutral setcdo).
        "cdo_title_key": "Interface_Product_Snack_CandyBar",
        "thumb_path": "/Game/VideoStore/asset/prop/Snack/Snack/T_Snack_Chocolat-A_T",
        "thumb_name": "T_Snack_Chocolat-A_T",
        "default_price": 2.0,
        "widget_sibling": "SnackBox_Snack_C",
        # TIER 2 — the vending box (the actual catalogue item).
        "box": {
            "pak_dir": "RetroRewind/Content/VideoStore/asset/prop/Snack",
            "asset": "SnackBox_Snack",
            "self_path": "/Game/VideoStore/asset/prop/Snack/SnackBox_Snack",
            "class_token": "SnackBox_Snack_C",
            "product_class": "Snack_Candy-A_C",   # array element renamed to <item>_C
        },
    },
    # Toy vending box — the PRODUCT owns its mesh (custom mesh OK); name is DERIVED
    # (product inherits Toys_Base_C, no title-key). Box parent = SnackBox_C.
    "toy": {
        "id": "toy", "label": "Toy (vending box)", "placement": "floor",
        "category": "Container",
        "pak_dir": "RetroRewind/Content/VideoStore/asset/prop/toys/Toys",
        "asset": "Toys_ToysShelf_A_01",
        "self_path": "/Game/VideoStore/asset/prop/toys/Toys/Toys_ToysShelf_A_01",
        "class_token": "Toys_ToysShelf_A_01_C",
        "mesh_path": "/Game/VideoStore/asset/meshes/LA_Toy_ToyShelf_A_01",
        "mesh_name": "LA_Toy_ToyShelf_A_01",
        # no cdo_title_key -> setcdo skipped, derived name.
        "default_price": 2.0,
        "widget_sibling": "ToysBox_C",
        "box": {
            "pak_dir": "RetroRewind/Content/VideoStore/asset/prop/toys",
            "asset": "ToysBox",
            "self_path": "/Game/VideoStore/asset/prop/toys/ToysBox",
            "class_token": "ToysBox_C",
            "product_class": "Toys_ToysShelf_A_01_C",
        },
    },
    # Drink vending box — product mesh INHERITS Drink_Base_C so keep_mesh (no custom
    # drink mesh without a Base decode); name DERIVED (no title-key). Box = DrinkBox,
    # parent SnackBox_Drink_C. (Full custom name+mesh = follow-up Base decode.)
    "drink": {
        "id": "drink", "label": "Drink (vending box)", "placement": "floor",
        "category": "Container", "keep_mesh": True,
        "pak_dir": "RetroRewind/Content/VideoStore/asset/prop/fridge/Soda",
        "asset": "Soda_Can-A_01",
        "self_path": "/Game/VideoStore/asset/prop/fridge/Soda/Soda_Can-A_01",
        "class_token": "Soda_Can-A_01_C",
        # keep_mesh: mesh ref unused; mesh_name set for _slot_tokens length math only.
        "mesh_path": "/Game/VideoStore/asset/meshes/Soda_Can-A_01",
        "mesh_name": "Soda_Can-A_01",
        "thumb_path": "/Game/VideoStore/asset/prop/fridge/Soda/T_Soda_Can-A_01_T",
        "thumb_name": "T_Soda_Can-A_01_T",
        # no cdo_title_key -> derived name.
        "default_price": 2.0,
        "widget_sibling": "DrinkBox_C",
        "box": {
            "pak_dir": "RetroRewind/Content/VideoStore/asset/prop/fridge",
            "asset": "DrinkBox",
            "self_path": "/Game/VideoStore/asset/prop/fridge/DrinkBox",
            "class_token": "DrinkBox_C",
            "product_class": "Soda_Can-A_01_C",
        },
    },
}

DEFAULT_EXEMPLAR = {"Decoration": "couch", "Equipmement": "arcade", "Container": "snack"}


def exemplars_for(category: str) -> list[dict]:
    """Base items the user can clone for a given content category."""
    return [e for e in EXEMPLARS.values() if e["category"] == category]


def get_exemplar(exemplar_id: str | None, category: str = "Decoration") -> dict:
    """Resolve the chosen exemplar id, falling back to the category default / first."""
    if exemplar_id and exemplar_id in EXEMPLARS:
        return EXEMPLARS[exemplar_id]
    lst = exemplars_for(category)
    return lst[0] if lst else EXEMPLARS["couch"]

# Length of the fixed affixes around the item token in the CDO title-key
# ("Interface_ModKit_" + <token> + "_Title"). Token length = key length - this.
_TITLE_AFFIX = len("Interface_ModKit_") + len("_Title")   # 17 + 6 = 23

# Import + cook a user FBX into a StaticMesh at a chosen /Game path. This half of the
# old cooker always worked (it was the stub BP that failed) — reused verbatim.
_MESH_COOK_SCRIPT = r'''
import unreal, traceback
LOG = r"%(log)s"
def note(m):
    try: open(LOG, "a").write(str(m) + "\n")
    except Exception: pass
FBX = r"%(fbx)s"; PKG = "%(pkg)s"; NM = "%(name)s"; PLACE = "%(place)s"
MIS = %(mis)s          # /Game/.../MI paths to retarget the mesh material slots onto
at = unreal.AssetToolsHelpers.get_asset_tools()
eal = unreal.EditorAssetLibrary
try:
    # Build our OWN material (import_materials=False): the mesh's slots are retargeted
    # to the game/cloned MIs below via stub MaterialInstanceConstants at those paths,
    # so the cooked import table resolves to the real (user-reskinned) MI at runtime —
    # the same stub-retarget trick the mesh-REPLACE cooker uses. This replaces the old
    # import_materials=True path, whose generic material + textures were never staged.
    opt = unreal.FbxImportUI()
    opt.import_mesh = True; opt.import_as_skeletal = False
    opt.import_materials = False; opt.import_textures = False
    opt.mesh_type_to_import = unreal.FBXImportType.FBXIT_STATIC_MESH
    opt.static_mesh_import_data.combine_meshes = True
    opt.static_mesh_import_data.auto_generate_collision = True
    task = unreal.AssetImportTask()
    task.filename = FBX; task.destination_path = PKG; task.destination_name = NM
    task.replace_existing = True; task.automated = True; task.save = True; task.options = opt
    at.import_asset_tasks([task])
    # Wall vs floor need DIFFERENT collision. The wall-placement ghost traces against
    # the mesh's SIMPLE collision. The vanilla PosterFrame uses a THIN, mesh-following
    # CONVEX (single hull, ~15cm deep, biased BEHIND the mount plane); a symmetric BOX
    # gets rejected by real walls (only the locker's flat top accepts a box) — the
    # "locker yes, walls no" bug. So wall items get a mesh-derived convex; floor items
    # keep the cheap box. Non-fatal — a mesh that can't take collision still cooks.
    mesh = unreal.load_asset(PKG + "/" + NM)
    if mesh is not None:
        sub = None
        try: sub = unreal.get_editor_subsystem(unreal.StaticMeshEditorSubsystem)
        except Exception: sub = None
        try:
            if sub is not None: sub.remove_collisions(mesh)
        except Exception: pass
        if PLACE == "wall":
            # Single convex hull from the mesh geometry — matches PosterFrame's cooked
            # convex (thin slab following the recentered mesh, which wall_recenter has
            # already biased to sit -11..+4cm across the wall normal like the vanilla).
            try:
                if sub is not None:
                    sub.set_convex_decomposition_collisions(mesh, 1, 24, 100000)
                else:
                    unreal.EditorStaticMeshLibrary.set_convex_decomposition_collisions(
                        mesh, 1, 24, 100000)
            except Exception as e2:
                note("COLLISION_WARN convex " + str(e2))
        else:
            try:
                if sub is not None:
                    sub.add_simple_collisions(mesh, unreal.ScriptingCollisionShapeType.BOX)
                else:
                    unreal.EditorStaticMeshLibrary.add_simple_collisions(
                        mesh, unreal.ScriptingCollisionShapeType.BOX)
            except Exception as e2:
                note("COLLISION_WARN box " + str(e2))
        # Retarget the mesh's material slots to the game/cloned MIs. Stub MICs at the
        # MI paths make the cooked import table reference them; the real reskinned MIs
        # are staged into the pak at those same paths (inject._stage_mesh_material).
        if MIS:
            base = unreal.load_asset("/Engine/BasicShapes/BasicShapeMaterial")
            mics = []
            for mi in MIS:
                pkg = mi.rsplit("/", 1)[0]; name = mi.rsplit("/", 1)[-1]
                if not eal.does_asset_exist(mi):
                    m = at.create_asset(name, pkg, unreal.MaterialInstanceConstant,
                                        unreal.MaterialInstanceConstantFactoryNew())
                    if base: m.set_editor_property("parent", base)
                    eal.save_asset(mi, only_if_is_dirty=False)
                mics.append(unreal.load_asset(mi))
            slots = mesh.get_editor_property("static_materials")
            if mics and slots:
                new = []
                for i in range(len(slots)):
                    mic = mics[min(i, len(mics) - 1)]
                    new.append(unreal.StaticMaterial(material_interface=mic,
                                                     material_slot_name="Mat%%d" %% i))
                mesh.set_editor_property("static_materials", new)
                mesh.modify()
            note("SLOTS %%d MICS %%d" %% (len(slots), len(mics)))
    unreal.EditorAssetLibrary.save_asset(PKG + "/" + NM, only_if_is_dirty=False)
    note("MESH_DONE " + PKG + "/" + NM)
except Exception:
    note("MESH_ERR\n" + traceback.format_exc())
'''


# ---------------------------------------------------------------------------
# relink.exe — the C# UAssetAPI tool. `clone` re-serialises an exemplar to a NEW
# package identity (+ optional mesh swap); the default (no-cmd) form inserts a
# class into the catalogue widget's product-class bytecode with the correct +9B
# cooked relink. Replaces the old byte-.replace clone AND the whole UE4SS/Lua path.
# ---------------------------------------------------------------------------
WIDGET_PAK_DIR = "RetroRewind/Content/VideoStore/asset/prop/catalogue"
WIDGET_ASSET = "UI_Catalogue_Widget"

# category -> (widget product-class fn, DEFAULT sibling class already in that array).
# The sibling is the widget import the new class is appended BESIDE; in-game
# placement/tab follows that neighbour. An item's exemplar may override the sibling
# per-item via `widget_sibling` (e.g. wall items anchor on PosterFrame_C, not Couch_C)
# — the pipeline prefers it["sibling"] and falls back to the default here.
# Equipment registers on its OWN product-class fn beside Pinball-Machine_A_C (verified
# present in UI_Catalogue_Widget imports; Arcade_C is not). Decoration/Container/Station
# still ride the proven Decoration fn until their own fn+sibling are verified in-game.
CAT_WIDGET = {
    "Decoration":  ("Return Catalogue Decoration product class", "Couch_C"),
    "Container":   ("Return Catalogue Container product class", "SnackBox_Snack_C"),
    "Equipmement": ("Return Catalogue Equipmement product class", "Pinball-Machine_A_C"),
    "Station":     ("Return Catalogue Decoration product class", "Couch_C"),
}


def _extract_widget(dest: Path) -> tuple[Path, Path]:
    """repak-unpack the vanilla catalogue widget out of the base pak."""
    core._repak("unpack", "-f", "-o", str(dest),
                "-i", f"{WIDGET_PAK_DIR}/{WIDGET_ASSET}.uasset",
                "-i", f"{WIDGET_PAK_DIR}/{WIDGET_ASSET}.uexp",
                str(core.base_pak()))
    d = dest / Path(*WIDGET_PAK_DIR.split("/"))
    return d / f"{WIDGET_ASSET}.uasset", d / f"{WIDGET_ASSET}.uexp"


INTERFACE_PAK_DIR = "RetroRewind/Content/VideoStore/localization/interface"
INTERFACE_ASSET = "Interface"


def _extract_interface(dest: Path) -> tuple[Path, Path]:
    """repak-unpack the vanilla Interface StringTable out of the base pak."""
    core._repak("unpack", "-f", "-o", str(dest),
                "-i", f"{INTERFACE_PAK_DIR}/{INTERFACE_ASSET}.uasset",
                "-i", f"{INTERFACE_PAK_DIR}/{INTERFACE_ASSET}.uexp",
                str(core.base_pak()))
    d = dest / Path(*INTERFACE_PAK_DIR.split("/"))
    return d / f"{INTERFACE_ASSET}.uasset", d / f"{INTERFACE_ASSET}.uexp"


def _title_key(item: str) -> str:
    """The per-item localization key stamped into the CDO + Interface StringTable."""
    return f"Interface_ModKit_{item}_Title"


def _slot_tokens(ex: dict, index: int) -> tuple[str, str]:
    """Unique, valid-FName tokens. The item token length is chosen so the CDO
    title-key `Interface_ModKit_<item>_Title` matches the exemplar's existing key
    byte length (LENGTH-NEUTRAL setcdo -> no CDO corruption). The mesh token keeps
    the exemplar mesh-name length (clone renames are any-length regardless)."""
    # keep_mesh (equipment) exemplars have no CDO title key (setcdo is skipped),
    # so the item-token length isn't constrained — use the Couch length (11).
    key = ex.get("cdo_title_key")
    ilen = (len(key) - _TITLE_AFFIX) if key else 11     # Couch: 34 - 23 = 11
    mlen = len(ex["mesh_name"])
    item = ("P" + str(index).zfill(ilen - 1))[:ilen]
    mesh = ("M" + format(index, "X").zfill(mlen - 1))[:mlen]
    return item, mesh


def _extract_exemplar(ex: dict, dest: Path) -> tuple[Path, Path]:
    """repak-unpack the exemplar's .uasset/.uexp out of the user's own base pak."""
    base = core.base_pak()
    core._repak("unpack", "-f", "-o", str(dest),
                "-i", f"{ex['pak_dir']}/{ex['asset']}.uasset",
                "-i", f"{ex['pak_dir']}/{ex['asset']}.uexp",
                str(base))
    d = dest / Path(*ex["pak_dir"].split("/"))
    return d / f"{ex['asset']}.uasset", d / f"{ex['asset']}.uexp"


def _clone_exemplar(ex: dict, item: str, mesh: str,
                    src_ua: Path, src_ux: Path, stage: Path,
                    thumb_token: str | None = None,
                    extra_renames: list[str] | None = None) -> dict:
    """RE-SERIALISE the exemplar into a NEW package identity (fresh PackageGuid +
    PackageSource + FolderName) pointing at the user's cooked mesh, via
    relink.clone (in-process, any-length exact name-map renames). Stages
    <item>.uasset/.uexp under the pak tree. When `thumb_token` is given, also
    repoints the catalogue thumbnail to the item's own texture (custom thumbnail).
    Returns {pkg_game, cls, ua, thumb_path}."""
    base = ex["self_path"].rsplit("/", 2)[0]            # .../decoration
    new_self = f"{base}/{item}/{item}"
    new_mesh_path = f"{ex['mesh_path'].rsplit('/', 1)[0]}/{mesh}"
    game_dir = new_self.rsplit("/", 1)[0]              # .../decoration/<item>
    mount_dir = "RetroRewind/Content/" + game_dir[len("/Game/"):]
    dest = stage / Path(*mount_dir.split("/"))
    dest.mkdir(parents=True, exist_ok=True)
    out_ua = dest / f"{item}.uasset"

    # trailing rename pairs: mesh package ref + mesh object name (renamed to the
    # user's cooked mesh) — UNLESS keep_mesh, where the clone reuses the vanilla
    # mesh (equipment: no user model), so the mesh ref must be left untouched.
    extra = [] if ex.get("keep_mesh") else [ex["mesh_path"], new_mesh_path,
                                            ex["mesh_name"], mesh]
    new_thumb_path = None
    if thumb_token:
        new_thumb_path = f"{game_dir}/{thumb_token}"
        extra += [ex["thumb_path"], new_thumb_path, ex["thumb_name"], thumb_token]

    # Equipment: repoint the BP's colour-MI references to the cloned MIs (old/new
    # package-path + object-leaf pairs computed by _stage_equipment_textures).
    if extra_renames:
        extra += list(extra_renames)

    relink.clone(src_ua, out_ua, ex["self_path"], new_self,
                 ex["class_token"], f"{item}_C", *extra)
    return {"pkg_game": new_self, "cls": f"{new_self}.{item}_C", "ua": out_ua,
            "thumb_path": new_thumb_path}


def _clone_container_box(ex: dict, item: str, product_self: str, stage: Path) -> dict:
    """TIER 2 (snack/drink/toy) — clone the vending BOX (the actual Container
    catalogue item) to a new identity, repoint the product-class it references to
    the just-cloned product (<item>_C at `product_self`), then box_repoint EVERY
    shelf slot to that product so the box shows/dispenses only the custom product.
    Returns {pkg_game, cls, ua} for the BOX — the entry that gets widget-registered.

    Assumes ex['box'] = {pak_dir, asset, self_path, class_token, product_class}. The
    box's name map holds the product class token AND the product's package path as
    imports; renaming both repoints the box's product import, then box_repoint fills
    all slots. (Rename strings VERIFIED present in the snack/toy/drink box name maps
    against the R: base pak 2026-07-07 — SnackBox_Snack_C / ToysBox_C / DrinkBox_C and
    each product class + package path all resolve.)"""
    box = ex["box"]
    box_item = item + "Box"
    box_base = box["self_path"].rsplit("/", 1)[0]              # .../Snack
    new_box_self = f"{box_base}/{box_item}/{box_item}"
    mount_dir = "RetroRewind/Content/" + new_box_self.rsplit("/", 1)[0][len("/Game/"):]
    dest = stage / Path(*mount_dir.split("/"))
    dest.mkdir(parents=True, exist_ok=True)
    out_ua = dest / f"{box_item}.uasset"

    import tempfile
    tmp = Path(tempfile.mkdtemp(prefix="pakrat_box_"))
    core._repak("unpack", "-f", "-o", str(tmp),
                "-i", f"{box['pak_dir']}/{box['asset']}.uasset",
                "-i", f"{box['pak_dir']}/{box['asset']}.uexp",
                str(core.base_pak()))
    src_ua = tmp / Path(*box["pak_dir"].split("/")) / f"{box['asset']}.uasset"

    # New box identity + repoint the referenced product (class token + package path)
    # to the cloned product, so slot 1 already points at it; box_repoint does the rest.
    relink.clone(src_ua, out_ua, box["self_path"], new_box_self,
                 box["class_token"], f"{box_item}_C",
                 box["product_class"], f"{item}_C",
                 ex["self_path"], product_self)
    relink.box_repoint(out_ua, out_ua, f"Default__{box_item}_C", f"{item}_C")
    return {"pkg_game": new_box_self, "cls": f"{new_box_self}.{box_item}_C", "ua": out_ua}


def _cook_user_mesh(env: "cook.CookEnv", fbx: str, mesh_token: str,
                    stage: Path, progress=None, placement: str | None = None,
                    mi_paths: "list[str] | None" = None) -> int:
    """Import+cook the user FBX to /Game/.../meshes/<mesh_token>, retarget its
    material slots onto `mi_paths` (the game/cloned MIs, staged separately by
    _stage_mesh_material), and stage the mesh. Returns files staged (0 => cook
    produced nothing)."""
    log = cook.home() / "inject_cook.log"
    try:
        log.unlink()
    except Exception:
        pass
    # Normalise ANY non-FBX source (incl. .uemodel from FModel) to FBX via Blender
    # before the UE import — UE's importer only reads FBX/OBJ. Pass-through for .fbx.
    fbx = cook.convert_to_fbx(env, fbx, progress=progress)
    # Wall-mounted items: shift the pivot to the mesh's back face so it mounts flush
    # against the wall (not half-buried) and its collision no longer penetrates.
    if placement == "wall":
        fbx = cook.wall_recenter(env, fbx, progress=progress)
    # The user's material textures ride on cloned MIs staged upstream
    # (_stage_mesh_material); the cook retargets the mesh's slots onto them via stub
    # MICs at those paths — the single texture path, no Blender material bake here.
    script = cook.project_dir() / "pakrat_mesh_import.py"
    script.write_text(_MESH_COOK_SCRIPT % {
        "log": str(log), "fbx": fbx, "pkg": MESH_ROOT, "name": mesh_token,
        "place": placement or "", "mis": repr(list(mi_paths or []))},
        encoding="utf-8")
    if progress:
        progress(f"Importing mesh '{mesh_token}'…", None)
    cook._ue(env, f"-ExecutePythonScript={script}")
    if progress:
        progress("Cooking mesh…", None)
    cook._ue(env, "-run=cook", "-targetplatform=Windows", "-unversioned",
             "-cookall", "-nozenstore")
    cooked_root = cook.project_dir() / "Saved" / "Cooked"
    matches = sorted(cooked_root.rglob(mesh_token + ".uasset")) if cooked_root.is_dir() else []
    if not matches:
        return 0
    src = matches[0]
    mount = "RetroRewind/Content/" + MESH_ROOT[len("/Game/"):]
    dest = stage / Path(*mount.split("/"))
    dest.mkdir(parents=True, exist_ok=True)
    n = 0
    for f in src.parent.glob(mesh_token + ".*"):
        if f.suffix in (".uasset", ".uexp", ".ubulk"):
            shutil.copy2(f, dest / f.name); n += 1
    return n


# ---------------------------------------------------------------------------
# Sound replace (D1) — swap ANY game USoundWave (arcade/pinball SFX, UI, music) for
# the user's audio by importing+cooking it IN AT the vanilla sound's own path, so the
# staged pak OVERRIDES it (the texture-override mechanism, for audio). Needs UE (cook)
# — Ares can't run it; testers do. Best-effort / non-fatal at the call site.
# ---------------------------------------------------------------------------
_SOUND_COOK_SCRIPT = r'''
import unreal, traceback
LOG = r"%(log)s"
def note(m):
    try: open(LOG, "a").write(str(m) + "\n")
    except Exception: pass
SND = r"%(audio)s"; PKG = "%(pkg)s"; NM = "%(name)s"
try:
    at = unreal.AssetToolsHelpers.get_asset_tools()
    task = unreal.AssetImportTask()
    task.filename = SND; task.destination_path = PKG; task.destination_name = NM
    task.replace_existing = True; task.automated = True; task.save = True
    at.import_asset_tasks([task])
    note("imported " + PKG + "/" + NM)
except Exception:
    note(traceback.format_exc())
'''


def _cook_user_sound(env: "cook.CookEnv", audio: str, target_game_path: str,
                     stage: Path, progress=None) -> int:
    """Import + cook `audio` to the SoundWave at `target_game_path` (/Game/...) and
    stage it there, so the pak overrides that vanilla sound. Returns files staged."""
    pkg, name = target_game_path.rsplit("/", 1)
    log = cook.home() / "inject_sound.log"
    try:
        log.unlink()
    except Exception:
        pass
    script = cook.project_dir() / "pakrat_sound_import.py"
    script.write_text(_SOUND_COOK_SCRIPT % {"log": str(log), "audio": audio,
                                            "pkg": pkg, "name": name}, encoding="utf-8")
    if progress:
        progress(f"Importing sound '{name}'…", None)
    cook._ue(env, f"-ExecutePythonScript={script}")
    if progress:
        progress("Cooking sound…", None)
    cook._ue(env, "-run=cook", "-targetplatform=Windows", "-unversioned",
             "-cookall", "-nozenstore")
    cooked_root = cook.project_dir() / "Saved" / "Cooked"
    matches = sorted(cooked_root.rglob(name + ".uasset")) if cooked_root.is_dir() else []
    if not matches:
        return 0
    src = matches[0]
    mount = "RetroRewind/Content/" + pkg[len("/Game/"):]
    dest = stage / Path(*mount.split("/"))
    dest.mkdir(parents=True, exist_ok=True)
    n = 0
    for f in src.parent.glob(name + ".*"):
        if f.suffix in (".uasset", ".uexp", ".ubulk"):
            shutil.copy2(f, dest / f.name); n += 1
    return n


def replace_sound(env: "cook.CookEnv", target_mount: str, user_audio: str,
                  stage: Path, progress=None) -> int:
    """Swap a game sound (any USoundWave — arcade/pinball SFX, UI, music) with the
    user's audio, cooked in at the vanilla sound's own path (override). `target_mount`
    accepts a 'RetroRewind/Content/…' mount or a '/Game/…' path."""
    gp = target_mount
    if gp.startswith("RetroRewind/Content/"):
        gp = "/Game/" + gp[len("RetroRewind/Content/"):]
    elif not gp.startswith("/Game/"):
        gp = "/Game/" + gp.lstrip("/")
    return _cook_user_sound(env, user_audio, gp, stage, progress=progress)


def run_sound_pipeline(items: list[dict], progress=None) -> str:
    """Replace one or more game sounds with the user's audio and pack them into ONE
    override pak. items = [{'sound': <mount, no ext>, 'audio': <wav/ogg path>}, …].
    Each sound is cooked in at its own path so the pak overrides it. Returns the pak
    path. Needs UE (the cook) — Ares can't run it; testers do."""
    import tempfile

    def say(m, p=None):
        if progress:
            progress(m)

    if not items:
        raise RuntimeError("No sounds to replace.")
    env = cook.setup(progress=progress)
    work = Path(tempfile.mkdtemp(prefix="pakrat_snd_"))
    stage = work / "stage"
    stage.mkdir(parents=True, exist_ok=True)
    n = len(items)
    staged = 0
    for i, it in enumerate(items, 1):
        leaf = it["sound"].rstrip("/").split("/")[-1]
        say(f"Replacing sound {leaf}  ({i}/{n})…")
        staged += replace_sound(env, it["sound"], it["audio"], stage, progress=progress)
    if staged == 0:
        raise RuntimeError("The UE cook produced no sound — see inject_sound.log in the "
                           "Pak Rat home folder.")
    say("Packaging .pak…")
    first = items[0]["sound"].rstrip("/").split("/")[-1]
    name = first if n == 1 else f"{first}_plus{n - 1}"
    out_pak = work / f"zzz_PakRat_{name}_snd_P.pak"
    core._repak("pack", "--version", core.PAK_VERSION, "--mount-point", core.PAK_MOUNT,
                "--path-hash-seed", core.PAK_SEED, str(stage), str(out_pak))
    say("Done.")
    return str(out_pak)


def build_added_item(env: "cook.CookEnv", fbx: str, display_name: str,
                     category: str, index: int, stage: Path,
                     price: float | None = None, maps: "dict | None" = None,
                     thumbnail: str | None = None, progress=None,
                     exemplar: str | None = None, screen: str | None = None) -> dict:
    """Cook the user's mesh + clone the type's exemplar to point at it, then stamp
    the item's CDO (custom name key + price) LENGTH-NEUTRALLY. Optional `thumbnail`
    gives a custom catalogue icon (best-effort; falls back to the default icon).
    `texture` (mesh skin) is deferred — bake it into the model. Returns the manifest
    entry {pkg, cls, name, category, price}."""
    ex = get_exemplar(exemplar, category)
    item, mesh = _slot_tokens(ex, index)
    keep_mesh = bool(ex.get("keep_mesh"))
    # Resolve the user's texture SET into {bc,n,ram}; omitted Normal/RAM are neutral-
    # filled (D3) so a replace never keeps a stale map. `bc` is the base-colour skin.
    mset = _resolve_maps(maps, stage)
    bc = mset.get("bc")
    # Equipment (keep_mesh) clones the base machine WHOLE — vanilla mesh + materials,
    # no user model — so there is no FBX to cook. Everything else cooks the user mesh.
    if not keep_mesh:
        # Give the cooked mesh the GAME's material with the USER's textures: clone the
        # exemplar mesh's MIs, repoint their bc/n/ram/ao to the user's maps (the single
        # texture path). With no user maps, retarget to the vanilla MIs as-is so the
        # mesh still wears the real game material (not the default checker).
        has_maps = bool(mset.get("bc") or mset.get("n") or mset.get("ram"))
        bp_material_renames: list[str] = []
        try:
            if has_maps:
                if progress:
                    progress("Applying your material textures…", None)
                mi_paths = _stage_mesh_material(ex, item, mset, stage)

                # The exemplar Blueprint may carry OverrideMaterials entries that
                # still point at the source mesh's materials.  Those overrides win
                # over the material slots cooked onto the replacement mesh, so also
                # repoint every source-material package/object reference in the BP
                # clone to the corresponding per-item cloned MI.
                source_mesh_mount = ex["mesh_path"].replace(
                    "/Game/", "RetroRewind/Content/", 1)
                source_mis = cook.resolve_mesh_materials(source_mesh_mount)
                for old_mi, new_mi in zip(source_mis, mi_paths):
                    bp_material_renames += [
                        old_mi, new_mi,
                        old_mi.rsplit("/", 1)[-1],
                        new_mi.rsplit("/", 1)[-1],
                    ]
            else:
                mesh_mount = ex["mesh_path"].replace("/Game/", "RetroRewind/Content/", 1)
                mi_paths = cook.resolve_mesh_materials(mesh_mount)
        except Exception as e:
            if progress:
                progress(f"Material textures skipped ({e}); using the mesh's own.", None)
            mi_paths = []
        if _cook_user_mesh(env, fbx, mesh, stage, progress=progress,
                           placement=ex.get("placement"), mi_paths=mi_paths) == 0:
            raise RuntimeError(
                f"Cook produced no mesh for '{display_name}'. The UE cook step likely "
                "failed; see inject_cook.log / last_cook.log in the Pak Rat home folder.")

    # Custom mesh skin (texture):
    #  - Decoration/cooked items: handled above via _stage_mesh_material (game
    #    material cloned with the user's bc/n/ram) — nothing deferred here anymore.
    #  - Equipment (keep_mesh) WITH colour materials: reskin the body base-colour
    #    texture from the user's image and repoint the cloned colour MIs to it, so
    #    only this new machine is recoloured (the Arcade_D recipe). Best-effort:
    #    a reskin hiccup falls back to the vanilla skin, never fails the add.
    mi_renames: list[str] = list(locals().get("bp_material_renames", []))
    if not keep_mesh:
        pass
    else:
        # Equipment body/colour: additive per-item MI reskin where the colour MIs are
        # BP-reachable (arcade), else an in-place texture override (pinball).
        if bc and ex.get("color_materials"):
            try:
                if progress:
                    progress("Reskinning the machine's colour…", None)
                mi_renames = _stage_equipment_textures(ex, item, mset, stage)
            except Exception as e:
                if progress:
                    progress(f"Colour reskin skipped ({e}); keeping the vanilla skin.", None)
                mi_renames = []
        elif bc and ex.get("body_override"):
            try:
                if progress:
                    progress("Reskinning the machine's colour…", None)
                _reskin_override(ex["body_override"], bc, stage)
            except Exception as e:
                if progress:
                    progress(f"Colour reskin skipped ({e}); keeping the vanilla skin.", None)
        # Equipment screen/display: override the video-screen texture in place.
        if screen and ex.get("screen_texture"):
            try:
                if progress:
                    progress("Reskinning the screen…", None)
                _reskin_override(ex["screen_texture"], screen, stage)
            except Exception as e:
                if progress:
                    progress(f"Screen reskin skipped ({e}); keeping the vanilla screen.", None)

    import tempfile
    tmp = Path(tempfile.mkdtemp(prefix="pakrat_ex_"))
    src_ua, src_ux = _extract_exemplar(ex, tmp)

    # Custom thumbnail — build it FIRST; only repoint the item to it if it fully
    # succeeds, otherwise keep the exemplar's icon (a real icon beats a blank one).
    # Best-effort and NON-FATAL: a thumbnail hiccup must never fail the whole add.
    thumb_token = None
    if thumbnail:
        try:
            if progress:
                progress("Building custom thumbnail…", None)
            tok = f"T_{item}_T"
            base = ex["self_path"].rsplit("/", 2)[0]            # .../decoration
            new_thumb_game = f"{base}/{item}/{tok}"             # matches _clone_exemplar
            _stage_custom_thumbnail(ex, thumbnail, new_thumb_game, tok, stage)
            thumb_token = tok                                   # success -> clone repoints to it
        except Exception as e:
            if progress:
                progress(f"Custom thumbnail skipped ({e}); using the default icon.", None)

    cloned = _clone_exemplar(ex, item, mesh, src_ua, src_ux, stage,
                             thumb_token=thumb_token, extra_renames=mi_renames)

    # CDO: swap the localisation title-key (name resolves via the StringTable set in
    # run_add_pipeline) AND set the price — both length-neutral in-place (the #6/#7
    # fix: token length was chosen so the key byte length is unchanged).
    p = float(price) if price is not None else ex.get("default_price", 0.0)
    is_container = ex.get("category") == "Container"
    if keep_mesh:
        # Equipment CDO layout differs from decorations (its title key is a
        # Statistic-LevelUp key, same byte length as Interface_ModKit_<item>_Title).
        # A swap that can't be applied length-neutrally must NOT fail the whole add —
        # fall back to the vanilla machine name/price. (In-game name = Yodah confirms.)
        try:
            relink.setcdo(cloned["ua"], cloned["ua"], f"Default__{item}_C",
                          _title_key(item), price=p)
        except Exception as e:
            if progress:
                progress(f"Custom equipment name/price skipped ({e}); vanilla kept.", None)
    elif is_container:
        # snack products own a title-key → custom NAME (name-only: a price would corrupt
        # the thumbnail refs that sit right after the key). toy/drink products inherit
        # from a *_Base with NO title-key → skip setcdo entirely (derived name), else
        # _find_title_key raises and sinks the whole add.
        if ex.get("cdo_title_key"):
            relink.setcdo(cloned["ua"], cloned["ua"], f"Default__{item}_C",
                          _title_key(item), price=None)
    else:
        relink.setcdo(cloned["ua"], cloned["ua"], f"Default__{item}_C",
                      _title_key(item), price=p)

    # TIER 2 (snack/drink/toy): the CATALOGUE item is the vending BOX, not the product.
    # Clone the box, repoint its product-class array to the just-cloned product, and
    # register the BOX — so the box shows/dispenses the user's custom product.
    if is_container and ex.get("box"):
        if progress:
            progress("Building the vending box…", None)
        box = _clone_container_box(ex, item, cloned["pkg_game"], stage)
        return {"pkg": box["pkg_game"], "cls": box["cls"], "name": display_name,
                "category": ex["category"], "price": p,
                "sibling": ex.get("widget_sibling"),
                # NAME is stamped on the PRODUCT CDO (Interface_ModKit_<item>_Title), not
                # the box — carry the product token so the StringTable binds to it. Only
                # snack products have a title-key; toy/drink are derived (name_token None).
                "name_token": item if ex.get("cdo_title_key") else None}

    return {"pkg": cloned["pkg_game"], "cls": cloned["cls"], "name": display_name,
            "category": ex["category"], "price": p,
            "sibling": ex.get("widget_sibling")}


# ---------------------------------------------------------------------------
# Custom texture / thumbnail — reskin an existing texture with the user's image
# via the vendored injector (encodes to the texture's own dxgi format + mips).
# The base texture is live-extracted from the game; the reskinned copy is then
# re-identitied to the item's own package path via relink.clone and staged.
# (UE/game-box paths — validated in Tron's in-game acceptance test.)
# ---------------------------------------------------------------------------
def _neutral_png(kind: str, size: "tuple[int, int]", dest: Path) -> Path:
    """Write a NEUTRAL default map PNG so a replaced material never keeps a stale map
    (D3). 'normal' -> flat normal RGB(128,128,255); 'ram' -> packed mask
    R=roughness(160) / G=AO white(255) / B=metallic(0); 'ao' -> white(255,255,255)
    (no occlusion — the exemplar's baked AO is meaningless on the user's mesh)."""
    from PIL import Image
    if kind == "normal":
        color = (128, 128, 255)
    elif kind == "ao":
        color = (255, 255, 255)
    else:                                   # ram
        color = (160, 255, 0)
    dest.parent.mkdir(parents=True, exist_ok=True)
    Image.new("RGB", (int(size[0]), int(size[1])), color).save(dest)
    return dest


def _resolve_maps(maps: "dict | str | None", stage: Path) -> "dict":
    """Normalise the caller's texture-set into {'bc','n','ram'} of file paths and
    enforce D3: if a Base Color (a real skin replace) is given, any omitted Normal /
    Packed-mask slot is filled with a generated NEUTRAL default so the material never
    inherits a stale map. Accepts a legacy single-path str (treated as base colour)."""
    if maps is None:
        return {"bc": None, "n": None, "ram": None}
    if isinstance(maps, str):
        maps = {"bc": maps}
    out = {"bc": maps.get("bc"), "n": maps.get("n"), "ram": maps.get("ram"),
           "ao": None}
    # Size the neutrals to the base-colour image when we have one, else a safe 1024².
    size = (1024, 1024)
    if out["bc"]:
        try:
            from PIL import Image
            with Image.open(out["bc"]) as im:
                size = im.size
        except Exception:
            pass
    if out["bc"] or out["n"] or out["ram"]:
        # Neutrals are SOURCE images for the inject — write them to a temp dir, never
        # under `stage` (that would pack the raw PNG into the mod). Omitted Normal/RAM
        # get neutral defaults; AO is ALWAYS neutral (D3 — the exemplar's baked AO is
        # meaningless on the user's mesh, so we never inherit it).
        import tempfile
        nd = Path(tempfile.mkdtemp(prefix="pakrat_neutral_"))
        if not out["n"]:
            out["n"] = str(_neutral_png("normal", size, nd / "neutral_n.png"))
        if not out["ram"]:
            out["ram"] = str(_neutral_png("ram", size, nd / "neutral_ram.png"))
        out["ao"] = str(_neutral_png("ao", size, nd / "neutral_ao.png"))
    return out


def _fit_token(seed: str, length: int) -> str:
    """Return a deterministic Unreal-safe token of exactly ``length`` characters."""
    import hashlib
    if length < 1:
        raise RuntimeError("cannot create an empty Unreal name token")
    digest = hashlib.sha1(seed.encode("utf-8")).hexdigest()
    token = (seed.replace("-", "_").replace(" ", "_") + "_" + digest)
    token = "".join(c if (c.isalnum() or c == "_") else "_" for c in token)
    if not token[0].isalpha() and token[0] != "_":
        token = "P" + token
    return (token + "_" * length)[:length]


def _length_neutral_texture_identity(old_game: str, item: str,
                                     mi_i: int, suffix: str) -> tuple[str, str]:
    """Create a unique package path/object name with the SAME byte lengths as the
    donor identity.  Equal-length replacement lets us rename the already-injected
    texture in-place without asking UAssetAPI to reserialize its mip/UBULK data.
    """
    old_leaf = old_game.rsplit("/", 1)[-1]
    leaf = _fit_token(f"T_PR_{item}_{mi_i:02d}_{suffix}", len(old_leaf))
    # Keep /Game/ and one generated folder.  The folder is padded so the complete
    # package path has exactly the donor path's ASCII byte length.
    folder_len = len(old_game) - len("/Game/") - 1 - len(leaf)
    if folder_len < 1:
        raise RuntimeError(f"donor texture path is too short to clone safely: {old_game}")
    folder = _fit_token(f"PakRat_{item}_{mi_i:02d}_{suffix}", folder_len)
    new_game = f"/Game/{folder}/{leaf}"
    if len(new_game.encode("ascii")) != len(old_game.encode("ascii")):
        raise RuntimeError("internal error creating length-neutral texture identity")
    return new_game, leaf


def _replace_equal_length(path: Path, pairs: list[tuple[str, str]]) -> int:
    """Patch exact ASCII name-map strings without shifting a cooked package.
    Returns the number of old-string occurrences replaced.
    """
    if not path.is_file():
        return 0
    data = path.read_bytes()
    count = 0
    for old, new in pairs:
        ob = old.encode("ascii")
        nb = new.encode("ascii")
        if len(ob) != len(nb):
            raise RuntimeError(f"non length-neutral rename: {old!r} -> {new!r}")
        n = data.count(ob)
        if n:
            data = data.replace(ob, nb)
            count += n
    path.write_bytes(data)
    return count


def _reskin_and_stage(base_mount: str, user_image: str, new_game_path: str,
                      old_leaf: str, new_leaf: str, stage: Path) -> tuple[str, str]:
    """Inject first, then rename with LENGTH-NEUTRAL byte edits.

    The proven MI patch worked because it injected the correct pixels and then cloned
    the texture, but UAssetAPI's clone rewrite discarded the large external mip data,
    leaving only the donor's 64x64 inline mip.  Cloning before injection preserved
    mips but broke the material reference.  This version keeps the proven order while
    avoiding UAssetAPI for the texture package itself: it injects the full-resolution
    image, copies every sidecar, and edits only equal-length package/object strings.
    No offsets move and .ubulk is preserved byte-for-byte.

    Returns the actual cloned /Game path and leaf used by the Material Instance.
    """
    spec = core.prepare_target(base_mount)
    try:
        injected = Path(spec.work_dir) / "reskin"
        core.replace_texture(base_mount, user_image, injected, spec=spec,
                             preserve_resolution=True)
        injected_ua = injected / f"{old_leaf}.uasset"
        if not injected_ua.is_file():
            raise RuntimeError("injector produced no output texture")

        old_game = base_mount.replace("RetroRewind/Content/", "/Game/", 1)
        # Derive the suffix/index from the requested identity, but generate an alias
        # whose package and object strings exactly match the donor lengths.
        try:
            mi_i = int(new_leaf.rsplit("_", 2)[-2])
        except Exception:
            mi_i = 0
        suffix = new_leaf.rsplit("_", 1)[-1]
        actual_game, actual_leaf = _length_neutral_texture_identity(
            old_game, new_leaf, mi_i, suffix)

        mount_dir = "RetroRewind/Content/" + actual_game.rsplit("/", 1)[0][len("/Game/"):]
        dest = stage / Path(*mount_dir.split("/"))
        dest.mkdir(parents=True, exist_ok=True)

        copied = []
        for ext in ("uasset", "uexp", "ubulk", "uptnl"):
            src = injected / f"{old_leaf}.{ext}"
            if not src.is_file():
                continue
            dst = dest / f"{actual_leaf}.{ext}"
            shutil.copy2(src, dst)
            copied.append(ext)

        if "uasset" not in copied:
            raise RuntimeError("failed to stage cloned texture")

        pairs = [(old_game, actual_game), (old_leaf, actual_leaf)]
        # Identity strings live in the package/name-map data, not the bulk pixels.
        # Patch only metadata-bearing files; leave .ubulk/.uptnl untouched.
        rename_hits = 0
        for ext in ("uasset", "uexp"):
            f = dest / f"{actual_leaf}.{ext}"
            rename_hits += _replace_equal_length(f, pairs)
        if rename_hits == 0:
            raise RuntimeError(
                f"texture identity was not found in {old_leaf}.uasset/.uexp")

        print(f"Pak Rat texture: {old_leaf} -> {actual_leaf}; "
              f"sidecars={copied}; rename_hits={rename_hits}")
        return actual_game, actual_leaf
    finally:
        core.cleanup_target(spec)


def _stage_custom_thumbnail(ex: dict, user_image: str, new_thumb_game_path: str,
                            thumb_token: str, stage: Path) -> None:
    """Build the item's catalogue thumbnail from `user_image`, re-identitied to the
    item's own thumbnail package path (the clone already repointed the CDO to it)."""
    _reskin_and_stage(
        base_mount=ex["thumb_path"].replace("/Game/", "RetroRewind/Content/", 1),
        user_image=user_image, new_game_path=new_thumb_game_path,
        old_leaf=ex["thumb_name"], new_leaf=thumb_token, stage=stage)


def _extract_game_asset(game_path: str, dest: Path) -> Path:
    """repak-unpack a single asset (.uasset + .uexp) by /Game path from the base
    pak. Returns the extracted .uasset. Used to pull the colour MIs to clone."""
    mount = game_path.replace("/Game/", "RetroRewind/Content/", 1)
    pak_dir, leaf = mount.rsplit("/", 1)
    core._repak("unpack", "-f", "-o", str(dest),
                "-i", f"{pak_dir}/{leaf}.uasset",
                "-i", f"{pak_dir}/{leaf}.uexp",
                str(core.base_pak()))
    return dest / Path(*pak_dir.split("/")) / f"{leaf}.uasset"


def _stage_equipment_textures(ex: dict, item: str, mset: "dict",
                              stage: Path) -> list[str]:
    """Recolour ONE equipment machine additively (the Arcade_D recipe): reskin the
    body base-colour texture from the user's image, then clone the colour MIs to new
    identities under the item's own /Game dir — the body MI repointed to the new
    texture. Returns the BP name-map rename pairs (old MI package-path + object-leaf
    -> new) so the cloned Blueprint references the new MIs (and thus the new skin)."""
    import tempfile
    base = ex["self_path"].rsplit("/", 2)[0]           # /Game/.../prop
    game_dir = f"{base}/{item}"                         # /Game/.../prop/<item>

    # 1) new body texture from the user's image, re-identitied under the item dir.
    body = ex["body_texture"]
    new_body_leaf = f"T_{item}_bc"
    new_body_game = f"{game_dir}/{new_body_leaf}"
    _reskin_and_stage(
        base_mount=body["path"].replace("/Game/", "RetroRewind/Content/", 1),
        user_image=mset["bc"], new_game_path=new_body_game,
        old_leaf=body["name"], new_leaf=new_body_leaf, stage=stage)

    # 2) clone each colour MI to a fresh identity under the item dir; the body MI
    #    also repoints its base-colour texture ref (path + leaf) to the new texture.
    renames: list[str] = []
    for i, mi in enumerate(ex["color_materials"]):
        new_mi_leaf = f"MI_{item}_{i:02d}"
        new_mi_game = f"{game_dir}/{new_mi_leaf}"
        tmp = Path(tempfile.mkdtemp(prefix="pakrat_mi_"))
        mi_ua = _extract_game_asset(mi["path"], tmp)
        mount_dir = "RetroRewind/Content/" + new_mi_game.rsplit("/", 1)[0][len("/Game/"):]
        dest = stage / Path(*mount_dir.split("/"))
        dest.mkdir(parents=True, exist_ok=True)
        out_ua = dest / f"{new_mi_leaf}.uasset"
        # an MI has no _C class/CDO -> the leaf name rides the old_cls/new_cls slot.
        tex_pairs = ([body["path"], new_body_game, body["name"], new_body_leaf]
                     if mi.get("body") else [])
        relink.clone(mi_ua, out_ua, mi["path"], new_mi_game,
                     mi["name"], new_mi_leaf, *tex_pairs)
        renames += [mi["path"], new_mi_game, mi["name"], new_mi_leaf]
    return renames


def _stage_mesh_material(ex: dict, item: str, mset: "dict", stage: Path) -> list[str]:
    """Give a cooked user mesh the GAME's material wearing the USER's textures (the
    robust texture path). For each material the exemplar's mesh uses: clone it to a
    per-item identity, and for each of its bc / n / ram / ao texture slots inject the
    user's matching map (omitted Normal/RAM -> neutral; AO always neutral, D3 — never
    inherit the exemplar's baked maps). The shared vanilla textures are never touched
    (clone-mode, via the single texture primitive). Returns the cloned MI /Game paths
    so the cook can retarget the cooked mesh's material slots onto them."""
    import tempfile
    # The Blueprint's source mesh and the material donor are separate concerns.
    # `mesh_path` must remain the mesh reference actually present in the cloned BP
    # so _clone_exemplar can replace it. `material_mesh_path` may point to a cleaner
    # self-contained asset whose material owns local bc/n/ram textures.
    material_mesh_path = ex.get("material_mesh_path", ex["mesh_path"])
    mesh_mount = material_mesh_path.replace("/Game/", "RetroRewind/Content/", 1)
    mis = cook.resolve_mesh_materials(mesh_mount)          # /Game/.../MI paths
    if not mis:
        return []
    base = ex["self_path"].rsplit("/", 2)[0]              # /Game/.../<prop parent>
    game_dir = f"{base}/{item}"                            # per-item dir
    slot_img = {"bc": mset.get("bc"), "n": mset.get("n"),
                "ram": mset.get("ram"), "ao": mset.get("ao")}
    new_mis: list[str] = []
    for mi_i, mi_game in enumerate(mis):
        tmp = Path(tempfile.mkdtemp(prefix="pakrat_mi_"))
        mi_ua = str(_extract_game_asset(mi_game, tmp))
        # Discover the texture-object references stored in the active Material
        # Instance parameter table.  The Chair uses shared library textures, but
        # those references still live in MI_Chair_A_01 and must be redirected.
        tex_refs: dict = {}
        for ref in core._scan_refs(mi_ua, mi_ua[:-7] + ".uexp"):
            if core._classify(ref) == "texture":
                ref_game = cook.mount_to_game(ref)
                suf = ref_game.rsplit("_", 1)[-1].lower()
                # Packed maps in this project are normally named *_ram.  Accept a
                # *_packed alias too so the redirection remains explicit.
                if suf == "packed":
                    suf = "ram"
                if suf in ("bc", "n", "ram", "ao"):
                    tex_refs.setdefault(suf, ref_game)
        if not tex_refs:
            raise RuntimeError(
                f"No Base/Normal/RAM/AO parameter textures were found in {mi_game}")
        # reskin each slot to a per-item texture identity + collect MI rename pairs
        tex_pairs: list[str] = []
        for suf, old_game in tex_refs.items():
            img = slot_img.get(suf)
            if not img:
                continue                                  # slot we don't drive
            old_mount = old_game.replace("/Game/", "RetroRewind/Content/", 1)
            old_leaf = old_game.rsplit("/", 1)[-1]
            new_leaf = f"T_{item}_{mi_i:02d}_{suf}"
            new_tex_game = f"{game_dir}/{new_leaf}"
            actual_game, actual_leaf = _reskin_and_stage(
                old_mount, img, new_tex_game, old_leaf, new_leaf, stage)
            tex_pairs += [old_game, actual_game, old_leaf, actual_leaf]
        if not tex_pairs:
            raise RuntimeError(
                f"No material texture parameters were redirected in {mi_game}")
        # Clone the active MI to a per-item identity. relink.clone rewrites both the
        # imported package path and object leaf for every discovered parameter
        # texture, which changes the MI parameter values rather than merely creating
        # unused texture assets.
        new_mi_leaf = f"MI_{item}_{mi_i:02d}"
        new_mi_game = f"{game_dir}/{new_mi_leaf}"
        mount_dir = "RetroRewind/Content/" + new_mi_game.rsplit("/", 1)[0][len("/Game/"):]
        dest = stage / Path(*mount_dir.split("/"))
        dest.mkdir(parents=True, exist_ok=True)
        out_ua = dest / f"{new_mi_leaf}.uasset"
        mi_leaf = mi_game.rsplit("/", 1)[-1]
        relink.clone(Path(mi_ua), out_ua, mi_game, new_mi_game,
                     mi_leaf, new_mi_leaf, *tex_pairs)
        new_mis.append(new_mi_game)
    return new_mis


def _reskin_override(tex: dict, user_image: str, stage: Path) -> None:
    """OVERRIDE-mode texture swap: inject the user's image and stage it at the
    texture's OWN vanilla path (the pak globally supplies new pixels — the PacMan
    mechanism). Used where the texture is applied by Blueprint/SKU logic rather than
    a clone-reachable MI (arcade screen, pinball body). Delegates to core.stage_texture
    (the single texture-replacement primitive, in-place)."""
    base_mount = tex["path"].replace("/Game/", "RetroRewind/Content/", 1)
    core.stage_texture(base_mount, user_image, stage)


def run_add_pipeline(items: list[dict], progress=None, reset: bool = False) -> dict:
    """
    items: [{'fbx': path, 'name': str, 'category': 'Decoration'}, …]
    Per item: cook the user's mesh, then RE-SERIALISE a fresh-identity clone of the
    type's exemplar pointing at that mesh. Then extract the vanilla catalogue widget
    and CHAIN-insert every manifest item's class into its product-class bytecode —
    NATIVE registration, NO UE4SS/Lua. Each item's staged files are kept in a permanent
    asset library (see asset_library) and EVERY run rebuilds ONE fixed-name V8B pak from
    the whole library — widget + StringTable + all clones + meshes + thumbnails — then
    overwrites the previous pak on deploy. So adds accumulate without bound and no earlier
    item is dropped. Manifest is additive across runs (it drives the widget insert).
    Returns {'pak': path, 'ini': path, 'items_by_cat': {...}}.
    """
    import tempfile

    def say(m, p=None):
        if progress:
            progress(m, p)

    env = cook.setup(progress=progress)   # UE cooker (for the user's mesh)

    work = Path(tempfile.mkdtemp(prefix="pakrat_add_"))
    stage = work / "stage"
    stage.mkdir(parents=True, exist_ok=True)      # repak needs the dir to exist

    # Global, ever-increasing slot index keeps every added class name unique.
    if reset:                       # #5: start from a clean catalogue on request
        reset_additions()
    existing = manifest_items()
    base_index = sum(len(v) for v in existing.values())
    built = []
    for i, it in enumerate(items):
        entry = build_added_item(
            env, it["fbx"], it.get("name") or f"PakRatItem{i}",
            it.get("category", "Decoration"), base_index + i, stage,
            price=it.get("price"), maps=it.get("maps"),
            thumbnail=it.get("thumbnail"), progress=progress,
            exemplar=it.get("exemplar"), screen=it.get("screen"))
        built.append(entry)

    # Persist THIS run's freshly-staged item files (mesh + CDO + thumbnail) into the
    # permanent library, then pull the ENTIRE library back into the stage — so the pak
    # we pack below carries every item ever added, not just this run's. This is what
    # stops a second Add from dropping the first item's assets. (`stage` holds only the
    # new items' files at this point; the widget + StringTable are staged further down.)
    lib = asset_library()
    _merge_tree(stage, lib)      # new items -> library (accumulate, unique paths)
    _merge_tree(lib, stage)      # whole library -> stage (older items restored)

    # Merge new items into the manifest (additive) — it drives the widget insert.
    items_by_cat = existing
    for e in built:
        items_by_cat.setdefault(e["category"], []).append(
            {"pkg": e["pkg"], "cls": e["cls"], "name": e["name"],
             "price": e.get("price"), "sibling": e.get("sibling"),
             "name_token": e.get("name_token")})

    # Register EVERY manifest item natively into the catalogue widget: start from a
    # fresh vanilla widget, chain one insert per item (each output feeds the next).
    say("Registering into the catalogue widget…", None)
    wtmp = Path(tempfile.mkdtemp(prefix="pakrat_wid_"))
    cur_ua, _ = _extract_widget(wtmp)
    n = 0
    for cat, lst in items_by_cat.items():
        fn, def_sib = CAT_WIDGET.get(cat, CAT_WIDGET["Decoration"])
        for it in lst:
            out_ua = wtmp / f"widget_{n}.uasset"
            # widget_insert wants the LEAF class name (P…_C), not the full object
            # path stored in it["cls"] (…/P.P…_C) — the import ObjectName + its
            # Default__<leaf> CDO import derive from the leaf.
            leaf_cls = it["cls"].rsplit(".", 1)[-1]
            # Per-item sibling (wall items anchor on PosterFrame_C; equipment on
            # Pinball-Machine_A_C), falling back to the category default.
            sib = it.get("sibling") or def_sib
            relink.widget_insert(cur_ua, out_ua, it["pkg"], leaf_cls, sib, fn)
            cur_ua = out_ua
            n += 1
    wdest = stage / Path(*WIDGET_PAK_DIR.split("/"))
    wdest.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(cur_ua, wdest / f"{WIDGET_ASSET}.uasset")
    shutil.copyfile(cur_ua.with_suffix(".uexp"), wdest / f"{WIDGET_ASSET}.uexp")

    # Custom display NAMES: rebuild the Interface StringTable from vanilla, add every
    # manifest item's per-item title key -> its display name, and stage it in the pak
    # (Grok's proven mechanism; the CDO title key set above resolves against this).
    say("Applying custom names…", None)
    stmp = Path(tempfile.mkdtemp(prefix="pakrat_st_"))
    cur_st, _ = _extract_interface(stmp)
    m = 0
    for cat, lst in items_by_cat.items():
        for it in lst:
            # Container items register the BOX but stamp the name on the PRODUCT CDO
            # (Interface_ModKit_<product-token>_Title) — bind the StringTable to that
            # token, not the box's pkg leaf, so the custom product name resolves.
            item = it.get("name_token") or it["pkg"].rsplit("/", 1)[-1]   # Pxxxx
            out_st = stmp / f"st_{m}.uasset"
            relink.staddkey(cur_st, out_st, _title_key(item), it["name"])
            cur_st = out_st
            m += 1
    sdest = stage / Path(*INTERFACE_PAK_DIR.split("/"))
    sdest.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(cur_st, sdest / f"{INTERFACE_ASSET}.uasset")
    shutil.copyfile(cur_st.with_suffix(".uexp"), sdest / f"{INTERFACE_ASSET}.uexp")

    # Pack V8B (FNameBasedCompression, NO path-hash seed): required so genuinely NEW
    # package paths are discoverable by the loader (V11's path-hash index is not).
    say("Packaging .pak (V8B)…", None)
    # ONE fixed-name pak for all additions — deploy copies it by basename, so each
    # rebuild overwrites the previous pak in ~mods instead of piling up conflicting
    # catalogue widgets. Extend-in-place = unlimited add-ons.
    out_pak = work / ADDITIONS_PAK
    core._repak("pack", "--version", core.MESH_PAK_VERSION, "--mount-point",
                core.PAK_MOUNT, str(stage), str(out_pak))

    ini = save_manifest(items_by_cat)
    say("Done.", 100)
    return {"pak": str(out_pak), "ini": str(ini), "items_by_cat": items_by_cat}
