"""
Pak Rat v3 — "Add Asset" injection engine.

Adds genuinely NEW content to Retro Rewind (not a swap). The catalogue lists
purchasable/placeable items via Blueprint functions
`Return Catalogue <Category> product class` inside UI_Catalogue_Widget. Editing
that widget's compiled bytecode by hand is a dead end (a correct edit is a full
Kismet recompile, not a byte insert). So v3 registers new items at RUNTIME with
a tiny UE4SS Lua mod that hooks those functions and appends the new class to the
returned array — proven in-game, no widget edit, no crash.

Pipeline:
  1. Cook the user's model into a Decoration-derived Blueprint at a NEW /Game
     path (reuses the v2 UE cooker) so it is a real, loadable class.
  2. Pack the cooked asset into a loose `_P.pak`.
  3. Generate a UE4SS Lua mod that LoadAsset()s each new class and appends it to
     its catalogue category at runtime, plus an INI manifest tracking everything
     added (so re-runs are idempotent / additive).

Requires UE4SS installed in the game (for the runtime hook) AND Unreal Engine
(for the cook). The GUI gates the mode on `ue4ss_available()`.
"""
from __future__ import annotations

import configparser
import datetime
import shutil
from pathlib import Path

import core
import cook
import relink

# Category -> the widget function that returns that category's class array.
CATEGORIES = ("Decoration", "Equipmement", "Station", "Container")
CATEGORY_LABELS = {
    "Decoration": "Decorations",
    "Equipmement": "Equipment",
    "Station": "Stations",
    "Container": "Shelves",
}
WIDGET_CLASS = ("/Game/VideoStore/asset/prop/catalogue/"
                "UI_Catalogue_Widget.UI_Catalogue_Widget_C")

MOD_NAME = "PakRatInjector"

# Content types shown on the v3 "what are you adding?" step. Each maps to a
# catalogue product-class function (`category`). Only types with mapped=True are
# selectable in the GUI; the rest are placeholders until their catalogue path is
# reverse-engineered and proven. Order = display order.
# Shelves(Container) + Equipment(Equipmement) use the SAME proven catalogue hook
# as Decoration — `Return Catalogue <category> product class` on UI_Catalogue_Widget,
# which the generated Lua already generalizes over. The cook yields a Decoration-
# derived BP; `category` just routes which catalogue tab it's appended to.
# Snacks/Drinks/Toys have NO hookable function (their product list is a static data
# array on a stock-box CDO — ToysBox/DrinkBox/ConcessionsShelf), so they stay gated.
CONTENT_TYPES = [
    {"key": "Shelves",    "category": "Container",   "mapped": True},
    {"key": "Decoration", "category": "Decoration",  "mapped": True},
    {"key": "Equipment",  "category": "Equipmement", "mapped": True},
    {"key": "Snacks",     "category": None,          "mapped": False},
    {"key": "Drinks",     "category": None,          "mapped": False},
    {"key": "Toys",       "category": None,          "mapped": False},
]


def mapped_content_types() -> list[dict]:
    return [t for t in CONTENT_TYPES if t["mapped"]]


def content_type(key: str) -> dict | None:
    for t in CONTENT_TYPES:
        if t["key"] == key:
            return t
    return None


# ---------------------------------------------------------------------------
# UE4SS discovery (mirrors cook.ue_available for the GUI gate)
# ---------------------------------------------------------------------------
def _game_binaries_dir() -> Path | None:
    """<...>/RetroRewind/RetroRewind/Binaries/Win64 — sibling of Content/Paks."""
    try:
        paks = core._rr_paks_dir()          # <...>/RetroRewind/Content/Paks
    except Exception:
        return None
    win64 = paks.parent.parent / "Binaries" / "Win64"
    return win64 if win64.is_dir() else None


def ue4ss_dir() -> Path | None:
    win64 = _game_binaries_dir()
    if not win64:
        return None
    d = win64 / "ue4ss"
    if (d / "UE4SS.dll").is_file() or (d / "Mods").is_dir():
        return d
    return None


def ue4ss_mods_dir() -> Path | None:
    d = ue4ss_dir()
    return (d / "Mods") if d else None


def ue4ss_available() -> bool:
    return ue4ss_dir() is not None


# ---------------------------------------------------------------------------
# Lua injector + INI manifest generation
# ---------------------------------------------------------------------------
_LUA_HEADER = """-- ============================================================
-- PakRat Injector  (auto-generated by Pak Rat v3 — do not hand-edit)
-- Registers added items into the Retro Rewind catalogue at runtime by
-- hooking the per-category product-class functions and appending the new
-- classes to the returned array. Proven mechanism; no widget bytecode edit.
-- Regenerate by re-running Pak Rat "Add Asset".
-- ============================================================
local WIDGET_CLASS = "%(widget)s"

-- items[category] = { { pkg=<package path>, cls=<class object path> }, ... }
local ITEMS = %(items)s

local function log(m) print("[PakRatInjector] " .. tostring(m) .. "\\n") end
local function valid(o) return o and o:IsValid() end
local function findObj(p) local ok,o = pcall(StaticFindObject, p); if ok then return o end return nil end

-- Resolve (loading if needed) every class up front; cache the UClass objects.
local RESOLVED = {}   -- category -> { classObj, ... }
local function resolveAll()
    for cat, list in pairs(ITEMS) do
        RESOLVED[cat] = RESOLVED[cat] or {}
        for _, it in ipairs(list) do
            local c = findObj(it.cls)
            if not valid(c) then pcall(LoadAsset, it.pkg); c = findObj(it.cls) end
            if valid(c) then
                RESOLVED[cat][#RESOLVED[cat] + 1] = c
                log("resolved " .. it.cls)
            else
                log("FAILED to load " .. it.cls)
            end
        end
    end
end

local function makeAppender(cat)
    return function(Context, ReturnValue)
        pcall(function()
            if ReturnValue == nil then return end
            local arr = ReturnValue:get(); if arr == nil then return end
            local list = RESOLVED[cat]; if not list then return end
            for _, c in ipairs(list) do
                if valid(c) then arr[arr:GetArrayNum() + 1] = c end
            end
        end)
    end
end

local hooked = false
local function register()
    if hooked then return end
    resolveAll()
    for _, cat in ipairs({ %(cats)s }) do
        if ITEMS[cat] then
            local fn = WIDGET_CLASS .. ":Return Catalogue " .. cat .. " product class"
            local ok = pcall(function() RegisterHook(fn, makeAppender(cat), function() end) end)
            log((ok and "hooked " or "hook FAILED ") .. fn)
        end
    end
    hooked = true
end

-- The widget class isn't loaded at startup; register when it first appears.
NotifyOnNewObject(WIDGET_CLASS, function() register() end)
log("loaded")
"""


def _lua_table(items_by_cat: dict[str, list[dict]]) -> str:
    """Render the ITEMS Lua table literal."""
    lines = ["{"]
    for cat, lst in items_by_cat.items():
        lines.append(f'  ["{cat}"] = {{')
        for it in lst:
            lines.append(f'    {{ pkg="{it["pkg"]}", cls="{it["cls"]}" }},')
        lines.append("  },")
    lines.append("}")
    return "\n".join(lines)


def write_injector_mod(items_by_cat: dict[str, list[dict]],
                       mods_dir: Path | None = None) -> Path:
    """Write the UE4SS Lua mod that registers every item. Returns the mod dir."""
    mods_dir = mods_dir or ue4ss_mods_dir()
    if not mods_dir:
        raise RuntimeError("UE4SS Mods folder not found — is UE4SS installed?")
    mod = mods_dir / MOD_NAME
    (mod / "Scripts").mkdir(parents=True, exist_ok=True)
    (mod / "enabled.txt").write_text("", encoding="utf-8")

    cats = ", ".join(f'"{c}"' for c in items_by_cat)
    lua = _LUA_HEADER % {
        "widget": WIDGET_CLASS,
        "items": _lua_table(items_by_cat),
        "cats": cats,
    }
    (mod / "Scripts" / "main.lua").write_text(lua, encoding="utf-8")

    # Ensure the mod is listed+enabled in mods.txt (UE4SS load list).
    _ensure_mods_txt(mods_dir)
    return mod


def _ensure_mods_txt(mods_dir: Path) -> None:
    txt = mods_dir / "mods.txt"
    line = f"{MOD_NAME} : 1"
    try:
        existing = txt.read_text(encoding="utf-8") if txt.is_file() else ""
    except Exception:
        existing = ""
    if MOD_NAME in existing:
        return
    sep = "" if existing.endswith("\n") or not existing else "\n"
    with txt.open("a", encoding="utf-8") as f:
        f.write(sep + line + "\n")


# ---------------------------------------------------------------------------
# INI manifest — the registry of record for everything Pak Rat has added.
# ---------------------------------------------------------------------------
def manifest_path() -> Path:
    return cook.home() / "additions.ini"


def load_manifest() -> configparser.ConfigParser:
    cp = configparser.ConfigParser()
    p = manifest_path()
    if p.is_file():
        cp.read(p, encoding="utf-8")
    return cp


def manifest_items() -> dict[str, list[dict]]:
    """Read the manifest into {category: [{pkg, cls, name}, ...]}."""
    cp = load_manifest()
    out: dict[str, list[dict]] = {}
    for sec in cp.sections():
        if not sec.startswith("item:"):
            continue
        d = cp[sec]
        cat = d.get("category", "Decoration")
        price = d.get("price", "")
        out.setdefault(cat, []).append({
            "pkg": d.get("pkg", ""), "cls": d.get("cls", ""),
            "name": d.get("name", sec[5:]),
            "price": float(price) if price else None,
        })
    return out


def save_manifest(items_by_cat: dict[str, list[dict]]) -> Path:
    cp = configparser.ConfigParser()
    cp["pakrat"] = {
        "version": core.APP_VERSION,
        "updated": datetime.datetime.now().isoformat(timespec="seconds"),
    }
    for cat, lst in items_by_cat.items():
        for it in lst:
            key = "item:" + it.get("name", it["cls"].rsplit(".", 1)[-1])
            cp[key] = {
                "category": cat, "name": it.get("name", ""),
                "pkg": it["pkg"], "cls": it["cls"],
                "price": str(it.get("price") if it.get("price") is not None else ""),
            }
    p = manifest_path()
    with p.open("w", encoding="utf-8") as f:
        cp.write(f)
    return p


def has_additions() -> bool:
    """True if any items were previously added (drives the Page-1 label flip)."""
    return bool(manifest_items())


def reset_additions() -> None:
    """Wipe the additions manifest AND the persistent asset library so the next Add
    starts from a genuinely clean catalogue (metadata + staged package files both go).
    Fixes #5: the manifest is additive and replays EVERY past item into each generated
    pak, so stale test entries showed up as extra catalogue items."""
    try:
        manifest_path().unlink()
    except FileNotFoundError:
        pass
    shutil.rmtree(asset_library(), ignore_errors=True)


# ---------------------------------------------------------------------------
# Persistent asset library — every added item's staged package files (the cloned
# item .uasset/.uexp carrying its CDO, the cooked mesh, the custom thumbnail) are
# kept here under their real pak-tree paths. Every Add then rebuilds ONE pak from
# the WHOLE library and overwrites the previous one, so the catalogue extends
# without bound and no earlier item is ever dropped. Without this store the pak
# only held the newest run's files, so a second Add killed the first item's assets.
# It lives in the writable Pak Rat home (LOCALAPPDATA/PakRat — survives app
# updates, unlike the read-only _internal bundle); additions.ini is its index.
# ---------------------------------------------------------------------------
ADDITIONS_PAK = "zzz_PakRat_Additions_P.pak"   # fixed name -> each deploy overwrites


def asset_library() -> Path:
    d = cook.home() / "asset_library"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _merge_tree(src: Path, dst: Path) -> None:
    """Copy every file under `src` into `dst`, preserving the relative pak-tree
    layout. Overwrites same-path files; leaves unrelated files in `dst` intact."""
    for p in src.rglob("*"):
        if p.is_file():
            out = dst / p.relative_to(src)
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, out)


# ---------------------------------------------------------------------------
# Cook: FBX -> Decoration-derived Blueprint at a NEW /Game path.
#
# EXPERIMENTAL (beta1): the runtime injection mechanism is proven in-game, but
# cooking a brand-new Decoration Blueprint (vs a swap) is new. The cooked BP
# derives from a stub `Decoration` whose parent import resolves to the REAL
# game Decoration class at runtime (same stub-retarget trick v2 uses for
# materials), so it is a genuine TSubclassOf<Decoration>. Product metadata
# (price/name) falls back to the base Decoration defaults for now.
# ---------------------------------------------------------------------------
# EXEMPLARS: a real, in-game, LOADABLE catalogue item per type that we CLONE.
# Deriving a new BP from a stub Decoration fails to load (the cooked class binds to
# the game's real Decoration_C at runtime and mismatches the stub it was compiled
# against). A clone of a real item instead INHERITS that item's correct link to the
# real base class for free — so it loads. We only rename it (new unique identity) and
# repoint its mesh, both as SAME-LENGTH byte edits (the one edit class proven 100%
# reliable — no offsets shift, no package rewrite, no UAssetAPI shipped).
#   self_path / class_token / mesh_path / mesh_name are the exact strings we swap.
#   `asset` len sets the item-token length; `mesh_name` len sets the mesh-token length.
MESH_ROOT = "/Game/VideoStore/asset/meshes"
EXEMPLARS = {
    "Decoration": {
        "category": "Decoration",
        "pak_dir": "RetroRewind/Content/VideoStore/asset/prop/decoration/Couch",
        "asset": "Couch",
        "self_path": "/Game/VideoStore/asset/prop/decoration/Couch/Couch",
        "class_token": "Couch_C",
        "mesh_path": "/Game/VideoStore/asset/meshes/LA_Chair_A_01",
        "mesh_name": "LA_Chair_A_01",
        # The CDO's inline localisation title-key. Its BYTE LENGTH sets the added
        # item's token length so relink.setcdo stays length-neutral (no CDO shift
        # -> no price-0 / blank-thumb / crash regression). See relink.setcdo.
        "cdo_title_key": "Interface_Product_Decoration_Couch",   # 34 chars
        # Catalogue thumbnail texture (a T_*_T in the item's own folder). Renamed by
        # clone + reskinned with the user's image when a custom thumbnail is given.
        "thumb_path": "/Game/VideoStore/asset/prop/decoration/Couch/T_Decoration_Couch_T",
        "thumb_name": "T_Decoration_Couch_T",
        "default_price": 100.0,
    },
    # Shelves/Equipment: add their own exemplar (a real shelf / fridge) once the
    # Decoration clone path is confirmed in-game; the machinery below is generic.
}

# Length of the fixed affixes around the item token in the CDO title-key
# ("Interface_ModKit_" + <token> + "_Title"). Token length = key length - this.
_TITLE_AFFIX = len("Interface_ModKit_") + len("_Title")   # 17 + 6 = 23

# Import + cook a user FBX into a StaticMesh at a chosen /Game path. This half of the
# old cooker always worked (it was the stub BP that failed) — reused verbatim.
_MESH_COOK_SCRIPT = r'''
import unreal, traceback
LOG = r"%(log)s"
def note(m):
    try: open(LOG, "a").write(str(m) + "\n")
    except Exception: pass
FBX = r"%(fbx)s"; PKG = "%(pkg)s"; NM = "%(name)s"
at = unreal.AssetToolsHelpers.get_asset_tools()
try:
    opt = unreal.FbxImportUI()
    opt.import_mesh = True; opt.import_as_skeletal = False
    opt.import_materials = True; opt.import_textures = True
    opt.mesh_type_to_import = unreal.FBXImportType.FBXIT_STATIC_MESH
    opt.static_mesh_import_data.combine_meshes = True
    task = unreal.AssetImportTask()
    task.filename = FBX; task.destination_path = PKG; task.destination_name = NM
    task.replace_existing = True; task.automated = True; task.save = True; task.options = opt
    at.import_asset_tasks([task])
    unreal.EditorAssetLibrary.save_asset(PKG + "/" + NM, only_if_is_dirty=False)
    note("MESH_DONE " + PKG + "/" + NM)
except Exception:
    note("MESH_ERR\n" + traceback.format_exc())
'''


# ---------------------------------------------------------------------------
# relink.exe — the C# UAssetAPI tool. `clone` re-serialises an exemplar to a NEW
# package identity (+ optional mesh swap); the default (no-cmd) form inserts a
# class into the catalogue widget's product-class bytecode with the correct +9B
# cooked relink. Replaces the old byte-.replace clone AND the whole UE4SS/Lua path.
# ---------------------------------------------------------------------------
WIDGET_PAK_DIR = "RetroRewind/Content/VideoStore/asset/prop/catalogue"
WIDGET_ASSET = "UI_Catalogue_Widget"

# category -> (widget product-class fn, sibling class already in that array).
# All added items currently register on the Decorations tab (proven path): the
# clone is Decoration-derived and Couch_C is its in-array sibling.
CAT_WIDGET = {
    "Decoration":  ("Return Catalogue Decoration product class", "Couch_C"),
    "Container":   ("Return Catalogue Decoration product class", "Couch_C"),
    "Equipmement": ("Return Catalogue Decoration product class", "Couch_C"),
    "Station":     ("Return Catalogue Decoration product class", "Couch_C"),
}


def _extract_widget(dest: Path) -> tuple[Path, Path]:
    """repak-unpack the vanilla catalogue widget out of the base pak."""
    core._repak("unpack", "-f", "-o", str(dest),
                "-i", f"{WIDGET_PAK_DIR}/{WIDGET_ASSET}.uasset",
                "-i", f"{WIDGET_PAK_DIR}/{WIDGET_ASSET}.uexp",
                str(core.base_pak()))
    d = dest / Path(*WIDGET_PAK_DIR.split("/"))
    return d / f"{WIDGET_ASSET}.uasset", d / f"{WIDGET_ASSET}.uexp"


INTERFACE_PAK_DIR = "RetroRewind/Content/VideoStore/localization/interface"
INTERFACE_ASSET = "Interface"


def _extract_interface(dest: Path) -> tuple[Path, Path]:
    """repak-unpack the vanilla Interface StringTable out of the base pak."""
    core._repak("unpack", "-f", "-o", str(dest),
                "-i", f"{INTERFACE_PAK_DIR}/{INTERFACE_ASSET}.uasset",
                "-i", f"{INTERFACE_PAK_DIR}/{INTERFACE_ASSET}.uexp",
                str(core.base_pak()))
    d = dest / Path(*INTERFACE_PAK_DIR.split("/"))
    return d / f"{INTERFACE_ASSET}.uasset", d / f"{INTERFACE_ASSET}.uexp"


def _title_key(item: str) -> str:
    """The per-item localization key stamped into the CDO + Interface StringTable."""
    return f"Interface_ModKit_{item}_Title"


def _slot_tokens(ex: dict, index: int) -> tuple[str, str]:
    """Unique, valid-FName tokens. The item token length is chosen so the CDO
    title-key `Interface_ModKit_<item>_Title` matches the exemplar's existing key
    byte length (LENGTH-NEUTRAL setcdo -> no CDO corruption). The mesh token keeps
    the exemplar mesh-name length (clone renames are any-length regardless)."""
    ilen = len(ex["cdo_title_key"]) - _TITLE_AFFIX      # Couch: 34 - 23 = 11
    mlen = len(ex["mesh_name"])
    item = ("P" + str(index).zfill(ilen - 1))[:ilen]
    mesh = ("M" + format(index, "X").zfill(mlen - 1))[:mlen]
    return item, mesh


def _extract_exemplar(ex: dict, dest: Path) -> tuple[Path, Path]:
    """repak-unpack the exemplar's .uasset/.uexp out of the user's own base pak."""
    base = core.base_pak()
    core._repak("unpack", "-f", "-o", str(dest),
                "-i", f"{ex['pak_dir']}/{ex['asset']}.uasset",
                "-i", f"{ex['pak_dir']}/{ex['asset']}.uexp",
                str(base))
    d = dest / Path(*ex["pak_dir"].split("/"))
    return d / f"{ex['asset']}.uasset", d / f"{ex['asset']}.uexp"


def _clone_exemplar(ex: dict, item: str, mesh: str,
                    src_ua: Path, src_ux: Path, stage: Path,
                    thumb_token: str | None = None) -> dict:
    """RE-SERIALISE the exemplar into a NEW package identity (fresh PackageGuid +
    PackageSource + FolderName) pointing at the user's cooked mesh, via
    relink.clone (in-process, any-length exact name-map renames). Stages
    <item>.uasset/.uexp under the pak tree. When `thumb_token` is given, also
    repoints the catalogue thumbnail to the item's own texture (custom thumbnail).
    Returns {pkg_game, cls, ua, thumb_path}."""
    base = ex["self_path"].rsplit("/", 2)[0]            # .../decoration
    new_self = f"{base}/{item}/{item}"
    new_mesh_path = f"{ex['mesh_path'].rsplit('/', 1)[0]}/{mesh}"
    game_dir = new_self.rsplit("/", 1)[0]              # .../decoration/<item>
    mount_dir = "RetroRewind/Content/" + game_dir[len("/Game/"):]
    dest = stage / Path(*mount_dir.split("/"))
    dest.mkdir(parents=True, exist_ok=True)
    out_ua = dest / f"{item}.uasset"

    # trailing rename pairs: mesh package ref + mesh object name (always); the
    # thumbnail package ref + object name (only for a custom thumbnail).
    extra = [ex["mesh_path"], new_mesh_path, ex["mesh_name"], mesh]
    new_thumb_path = None
    if thumb_token:
        new_thumb_path = f"{game_dir}/{thumb_token}"
        extra += [ex["thumb_path"], new_thumb_path, ex["thumb_name"], thumb_token]

    relink.clone(src_ua, out_ua, ex["self_path"], new_self,
                 ex["class_token"], f"{item}_C", *extra)
    return {"pkg_game": new_self, "cls": f"{new_self}.{item}_C", "ua": out_ua,
            "thumb_path": new_thumb_path}


def _cook_user_mesh(env: "cook.CookEnv", fbx: str, mesh_token: str,
                    stage: Path, progress=None) -> int:
    """Import+cook the user FBX to /Game/.../meshes/<mesh_token> and stage it.
    Returns files staged (0 => cook produced nothing)."""
    log = cook.home() / "inject_cook.log"
    try:
        log.unlink()
    except Exception:
        pass
    script = cook.project_dir() / "pakrat_mesh_import.py"
    script.write_text(_MESH_COOK_SCRIPT % {
        "log": str(log), "fbx": fbx, "pkg": MESH_ROOT, "name": mesh_token},
        encoding="utf-8")
    if progress:
        progress(f"Importing mesh '{mesh_token}'…", None)
    cook._ue(env, f"-ExecutePythonScript={script}")
    if progress:
        progress("Cooking mesh…", None)
    cook._ue(env, "-run=cook", "-targetplatform=Windows", "-unversioned",
             "-cookall", "-nozenstore")
    cooked_root = cook.project_dir() / "Saved" / "Cooked"
    matches = sorted(cooked_root.rglob(mesh_token + ".uasset")) if cooked_root.is_dir() else []
    if not matches:
        return 0
    src = matches[0]
    mount = "RetroRewind/Content/" + MESH_ROOT[len("/Game/"):]
    dest = stage / Path(*mount.split("/"))
    dest.mkdir(parents=True, exist_ok=True)
    n = 0
    for f in src.parent.glob(mesh_token + ".*"):
        if f.suffix in (".uasset", ".uexp", ".ubulk"):
            shutil.copy2(f, dest / f.name); n += 1
    return n


def build_added_item(env: "cook.CookEnv", fbx: str, display_name: str,
                     category: str, index: int, stage: Path,
                     price: float | None = None, texture: str | None = None,
                     thumbnail: str | None = None, progress=None) -> dict:
    """Cook the user's mesh + clone the type's exemplar to point at it, then stamp
    the item's CDO (custom name key + price) LENGTH-NEUTRALLY. Optional `thumbnail`
    gives a custom catalogue icon (best-effort; falls back to the default icon).
    `texture` (mesh skin) is deferred — bake it into the model. Returns the manifest
    entry {pkg, cls, name, category, price}."""
    ex = EXEMPLARS.get(category) or EXEMPLARS["Decoration"]
    item, mesh = _slot_tokens(ex, index)
    if _cook_user_mesh(env, fbx, mesh, stage, progress=progress) == 0:
        raise RuntimeError(
            f"Cook produced no mesh for '{display_name}'. The UE cook step likely "
            "failed; see inject_cook.log / last_cook.log in the Pak Rat home folder.")

    # Custom mesh skin (texture) is DEFERRED: a real skin swap needs the cook to
    # emit + ship the model's own base-colour texture (game-box work). Bake the
    # texture into your model for now. Never fatal — just a note. (The earlier path
    # wrongly injected the image into the MESH uasset, which crashed the build.)
    if texture and progress:
        progress("Note: a separate skin isn't applied yet — bake it into your "
                 "model. Continuing…", None)

    import tempfile
    tmp = Path(tempfile.mkdtemp(prefix="pakrat_ex_"))
    src_ua, src_ux = _extract_exemplar(ex, tmp)

    # Custom thumbnail — build it FIRST; only repoint the item to it if it fully
    # succeeds, otherwise keep the exemplar's icon (a real icon beats a blank one).
    # Best-effort and NON-FATAL: a thumbnail hiccup must never fail the whole add.
    thumb_token = None
    if thumbnail:
        try:
            if progress:
                progress("Building custom thumbnail…", None)
            tok = f"T_{item}_T"
            base = ex["self_path"].rsplit("/", 2)[0]            # .../decoration
            new_thumb_game = f"{base}/{item}/{tok}"             # matches _clone_exemplar
            _stage_custom_thumbnail(ex, thumbnail, new_thumb_game, tok, stage)
            thumb_token = tok                                   # success -> clone repoints to it
        except Exception as e:
            if progress:
                progress(f"Custom thumbnail skipped ({e}); using the default icon.", None)

    cloned = _clone_exemplar(ex, item, mesh, src_ua, src_ux, stage,
                             thumb_token=thumb_token)

    # CDO: swap the localisation title-key (name resolves via the StringTable set in
    # run_add_pipeline) AND set the price — both length-neutral in-place (the #6/#7
    # fix: token length was chosen so the key byte length is unchanged).
    p = float(price) if price is not None else ex.get("default_price", 0.0)
    relink.setcdo(cloned["ua"], cloned["ua"], f"Default__{item}_C",
                  _title_key(item), price=p)
    return {"pkg": cloned["pkg_game"], "cls": cloned["cls"], "name": display_name,
            "category": ex["category"], "price": p}


# ---------------------------------------------------------------------------
# Custom texture / thumbnail — reskin an existing texture with the user's image
# via the vendored injector (encodes to the texture's own dxgi format + mips).
# The base texture is live-extracted from the game; the reskinned copy is then
# re-identitied to the item's own package path via relink.clone and staged.
# (UE/game-box paths — validated in Tron's in-game acceptance test.)
# ---------------------------------------------------------------------------
def _reskin_and_stage(base_mount: str, user_image: str, new_game_path: str,
                      old_leaf: str, new_leaf: str, stage: Path) -> None:
    """Extract `base_mount` from the game, inject `user_image` (the injector WRITES
    the modified asset into --save_folder, it does not edit in place), re-identity
    the result to `new_game_path`, and stage it under the pak."""
    spec = core.prepare_target(base_mount)               # extract + read dxgi/WxH
    try:
        prepared = core.prepare_image(user_image, spec)  # resize to the target WxH
        injected = Path(spec.work_dir) / "reskin"
        injected.mkdir(parents=True, exist_ok=True)
        core._injector([spec.uasset_path, prepared.prepared_png, "--mode", "inject",
                        "--version", core.UE_VERSION, "--save_folder", str(injected)])
        injected_ua = injected / f"{old_leaf}.uasset"
        if not injected_ua.is_file():
            raise RuntimeError("injector produced no output texture")
        mount_dir = "RetroRewind/Content/" + new_game_path.rsplit("/", 1)[0][len("/Game/"):]
        dest = stage / Path(*mount_dir.split("/"))
        dest.mkdir(parents=True, exist_ok=True)
        out_ua = dest / f"{new_leaf}.uasset"
        old_game = base_mount.replace("RetroRewind/Content/", "/Game/", 1)
        # a texture has no _C class/CDO -> pass '-' to skip those renames; just repath.
        relink.clone(injected_ua, out_ua, old_game, new_game_path,
                     old_leaf, new_leaf, "-", "-")
    finally:
        core.cleanup_target(spec)


def _stage_custom_thumbnail(ex: dict, user_image: str, new_thumb_game_path: str,
                            thumb_token: str, stage: Path) -> None:
    """Build the item's catalogue thumbnail from `user_image`, re-identitied to the
    item's own thumbnail package path (the clone already repointed the CDO to it)."""
    _reskin_and_stage(
        base_mount=ex["thumb_path"].replace("/Game/", "RetroRewind/Content/", 1),
        user_image=user_image, new_game_path=new_thumb_game_path,
        old_leaf=ex["thumb_name"], new_leaf=thumb_token, stage=stage)


def run_add_pipeline(items: list[dict], progress=None, reset: bool = False) -> dict:
    """
    items: [{'fbx': path, 'name': str, 'category': 'Decoration'}, …]
    Per item: cook the user's mesh, then RE-SERIALISE a fresh-identity clone of the
    type's exemplar pointing at that mesh. Then extract the vanilla catalogue widget
    and CHAIN-insert every manifest item's class into its product-class bytecode —
    NATIVE registration, NO UE4SS/Lua. Each item's staged files are kept in a permanent
    asset library (see asset_library) and EVERY run rebuilds ONE fixed-name V8B pak from
    the whole library — widget + StringTable + all clones + meshes + thumbnails — then
    overwrites the previous pak on deploy. So adds accumulate without bound and no earlier
    item is dropped. Manifest is additive across runs (it drives the widget insert).
    Returns {'pak': path, 'ini': path, 'items_by_cat': {...}}.
    """
    import tempfile

    def say(m, p=None):
        if progress:
            progress(m, p)

    env = cook.setup(progress=progress)   # UE cooker (for the user's mesh)

    work = Path(tempfile.mkdtemp(prefix="pakrat_add_"))
    stage = work / "stage"
    stage.mkdir(parents=True, exist_ok=True)      # repak needs the dir to exist

    # Global, ever-increasing slot index keeps every added class name unique.
    if reset:                       # #5: start from a clean catalogue on request
        reset_additions()
    existing = manifest_items()
    base_index = sum(len(v) for v in existing.values())
    built = []
    for i, it in enumerate(items):
        entry = build_added_item(
            env, it["fbx"], it.get("name") or f"PakRatItem{i}",
            it.get("category", "Decoration"), base_index + i, stage,
            price=it.get("price"), texture=it.get("texture"),
            thumbnail=it.get("thumbnail"), progress=progress)
        built.append(entry)

    # Persist THIS run's freshly-staged item files (mesh + CDO + thumbnail) into the
    # permanent library, then pull the ENTIRE library back into the stage — so the pak
    # we pack below carries every item ever added, not just this run's. This is what
    # stops a second Add from dropping the first item's assets. (`stage` holds only the
    # new items' files at this point; the widget + StringTable are staged further down.)
    lib = asset_library()
    _merge_tree(stage, lib)      # new items -> library (accumulate, unique paths)
    _merge_tree(lib, stage)      # whole library -> stage (older items restored)

    # Merge new items into the manifest (additive) — it drives the widget insert.
    items_by_cat = existing
    for e in built:
        items_by_cat.setdefault(e["category"], []).append(
            {"pkg": e["pkg"], "cls": e["cls"], "name": e["name"],
             "price": e.get("price")})

    # Register EVERY manifest item natively into the catalogue widget: start from a
    # fresh vanilla widget, chain one insert per item (each output feeds the next).
    say("Registering into the catalogue widget…", None)
    wtmp = Path(tempfile.mkdtemp(prefix="pakrat_wid_"))
    cur_ua, _ = _extract_widget(wtmp)
    n = 0
    for cat, lst in items_by_cat.items():
        fn, sib = CAT_WIDGET.get(cat, CAT_WIDGET["Decoration"])
        for it in lst:
            out_ua = wtmp / f"widget_{n}.uasset"
            # widget_insert wants the LEAF class name (P…_C), not the full object
            # path stored in it["cls"] (…/P.P…_C) — the import ObjectName + its
            # Default__<leaf> CDO import derive from the leaf.
            leaf_cls = it["cls"].rsplit(".", 1)[-1]
            relink.widget_insert(cur_ua, out_ua, it["pkg"], leaf_cls, sib, fn)
            cur_ua = out_ua
            n += 1
    wdest = stage / Path(*WIDGET_PAK_DIR.split("/"))
    wdest.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(cur_ua, wdest / f"{WIDGET_ASSET}.uasset")
    shutil.copyfile(cur_ua.with_suffix(".uexp"), wdest / f"{WIDGET_ASSET}.uexp")

    # Custom display NAMES: rebuild the Interface StringTable from vanilla, add every
    # manifest item's per-item title key -> its display name, and stage it in the pak
    # (Grok's proven mechanism; the CDO title key set above resolves against this).
    say("Applying custom names…", None)
    stmp = Path(tempfile.mkdtemp(prefix="pakrat_st_"))
    cur_st, _ = _extract_interface(stmp)
    m = 0
    for cat, lst in items_by_cat.items():
        for it in lst:
            item = it["pkg"].rsplit("/", 1)[-1]     # Pxxxx
            out_st = stmp / f"st_{m}.uasset"
            relink.staddkey(cur_st, out_st, _title_key(item), it["name"])
            cur_st = out_st
            m += 1
    sdest = stage / Path(*INTERFACE_PAK_DIR.split("/"))
    sdest.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(cur_st, sdest / f"{INTERFACE_ASSET}.uasset")
    shutil.copyfile(cur_st.with_suffix(".uexp"), sdest / f"{INTERFACE_ASSET}.uexp")

    # Pack V8B (FNameBasedCompression, NO path-hash seed): required so genuinely NEW
    # package paths are discoverable by the loader (V11's path-hash index is not).
    say("Packaging .pak (V8B)…", None)
    # ONE fixed-name pak for all additions — deploy copies it by basename, so each
    # rebuild overwrites the previous pak in ~mods instead of piling up conflicting
    # catalogue widgets. Extend-in-place = unlimited add-ons.
    out_pak = work / ADDITIONS_PAK
    core._repak("pack", "--version", core.MESH_PAK_VERSION, "--mount-point",
                core.PAK_MOUNT, str(stage), str(out_pak))

    ini = save_manifest(items_by_cat)
    say("Done.", 100)
    return {"pak": str(out_pak), "ini": str(ini), "items_by_cat": items_by_cat}
